[Botskills] Update Tool documentation
microsoft/botframework-solutions pull request #1342
Opened 2019-05-10 22:27 UTC by dfavretto

## Description

- Update Technical documentation
    - Update `connect` command documentation
    - Update `disconnect` command documentation
    - Update `list` command documentation
- Update How-to documentation with latest changes on the Tool
- Fix some broken links

## Testing Steps
1. Read the documentation.
1. Test the different steps that were modified.
1. Test the fixed links.

## Checklist
- [x] I have updated related documentation

2019-05-11 00:54 UTC, darrenj commented on docs/howto/skills/addingskills.md
> -npm install -g botdispatch, botskills
If the user doesn't have the dispatch tool installed this will cause the tool to not work?

2019-05-13 14:36 UTC, dfavretto commented on docs/howto/skills/addingskills.md
> -npm install -g botdispatch, botskills
hey @darrenj the Dispatch tool isn't needed installed globally, since it's being used as a dependency. However, with your comment you made me realize the LUISGen and LuDown tools **are required to be installed globally**, so I'll update the documentation with that prerequisite.

2019-05-13 16:05 UTC, lzc850612 requested changes

2019-05-13 16:05 UTC, lzc850612 commented on docs/howto/skills/addingskills.md
> -npm install -g botdispatch, botskills
Would it be better if we require Dispatch to be installed globally? It reduces the chance the developers forget to install it and make it easier for them.

2019-05-14 04:41 UTC, darrenj commented on docs/howto/skills/addingskills.md
> -npm install -g botdispatch, botskills
Yeah - I think that's probably best as people can dispatch refresh the bot directly?

2019-05-14 13:20 UTC, dfavretto commented on docs/howto/skills/addingskills.md
> -npm install -g botdispatch, botskills
@darrenj @lzc850612 the Dispatch tool is already a Dependency for Botskills, so the developer doesn't need to install it himself/herself. If you think it's better to have it despite all this, I'll add it anyway.

2019-05-14 16:56 UTC, lzc850612 approved these changes

2019-05-15 20:57 UTC, merged