inject all body items in GetCardResponse (#1710)
microsoft/botframework-solutions pull request #1729
Opened 2019-07-04 08:59 UTC by xieofxie

## Purpose
*What is the context of this pull request? Why is it being done?*

All body items should be injected.
If AdaptiveCard could be converted to AdaptiveContainer, the injection could be more consistent..

## Changes
*Are there any changes that need to be called out as significant or particularly difficult to grasp?*

*Include illustrative screenshots for context if applicable.*

No.

## Tests
*Is this covered by existing tests or new ones? If no, why not?*

N/A.

## Feature Plan
*Are there any remaining steps or dependencies before this issue can be fully resolved? If so, describe and link to any relevant pull requests or issues.*

N/A.

2019-07-09 12:46 UTC, ryanisgrig approved these changes

2019-07-09 15:10 UTC, lauren-mills approved these changes

2019-07-09 19:25 UTC, lzc850612 requested changes

2019-07-09 19:25 UTC, lzc850612 commented on lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Responses/ResponseManager.cs
>                  if ((itemsContainer != null) && itemsContainer is AdaptiveContainer)
let's declare a variable here with

itemsContainer is AdaptiveContainer adaptiveContainer

so we can use it later on line 186 instead of doing the cast again.

2019-07-10 03:48 UTC, xieofxie commented on lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Responses/ResponseManager.cs
>                  if ((itemsContainer != null) && itemsContainer is AdaptiveContainer)
OK, pushed.

2019-07-10 18:48 UTC, lzc850612 requested changes

2019-07-10 18:48 UTC, lzc850612 commented on lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Responses/ResponseManager.cs
> +                    var itemsAdaptiveContainer = itemsContainer as AdaptiveContainer;
line #180 is not needed. you can do this in line 178:
if (itemsContainer is AdaptiveContainer itemsAdaptiveContainer) and you can just use 'itemsAdaptiveContainer' going forward

2019-07-11 03:46 UTC, xieofxie commented on lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Responses/ResponseManager.cs
> +                    var itemsAdaptiveContainer = itemsContainer as AdaptiveContainer;
Cool, thanks!

2019-07-11 23:16 UTC, lzc850612 approved these changes

2019-07-15 04:12 UTC, merged