Update to automotive settings
microsoft/botframework-solutions pull request #1917
Opened 2019-07-22 20:00 UTC by Dewain27

Corrected settings from right and left to passenger / driver.

### Purpose
*What is the context of this pull request? Why is it being done?*

### Changes
*Are there any changes that need to be called out as significant or particularly difficult to grasp? (Include illustrative screenshots for context if applicable.)*

### Tests
*Is this covered by existing tests or new ones? If no, why not?*

### Feature Plan
*Are there any remaining steps or dependencies before this issue can be fully resolved? If so, describe and link to any relevant pull requests or issues.*

### Checklist

#### General
- [ ] I have commented my code, particularly in hard-to-understand areas	
- [ ] I have added or updated the appropriate tests	
- [ ] I have updated related documentation

#### Bots
- [ ] I have validated that new and updated responses use appropriate [Speak](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-text-to-speech?view=azure-bot-service-3.0) and [InputHint](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-add-input-hints?view=azure-bot-service-3.0) properties to ensure a high-quality speech-first experience
- [ ] I have replicated language model changes across the English, French, Italian, German, Spanish, and Chinese `.lu` files and validated that deployment is successful

#### Deployment Scripts
- [ ] I have replicated my changes in the **Virtual Assistant Template** and **Sample** projects
- [ ] I have replicated my changes in the **Skill Template** and **Sample** projects

2019-07-23 17:19 UTC, lauren-mills commented
@Dewain27 these changes broke the automotive tests. You'll need to go in and run the tests locally to fix them.

2019-07-23 18:44 UTC, darrenj approved these changes

2019-07-23 22:07 UTC, lauren-mills requested changes
The tests should be updated to reflect these changes.

2019-08-08 00:19 UTC, lauren-mills commented
@dewain After looking into fixing these tests, they are not behaving as expected which makes me think this is a more complicated change than just changing these setting names. I think we should close this and open an issue in the backlog. 

Also, changing to "driver" and "passenger" may not be the right call, considering different vehicles in different regions. Not sure about that one though.

2019-08-08 00:19 UTC, closed without merging