Update Telemetry Link to point to ABS docs
microsoft/botframework-solutions pull request #1941
Opened 2019-07-24 22:02 UTC by Dewain27

### Purpose
Changed to address the fact that Telemetry documentation is owned by ABS now and this should redirect to them.

### Changes
No

### Tests
*Is this covered by existing tests or new ones? If no, why not?*

### Feature Plan
*Are there any remaining steps or dependencies before this issue can be fully resolved? If so, describe and link to any relevant pull requests or issues.*

### Checklist

#### General
- [ ] I have commented my code, particularly in hard-to-understand areas	
- [ ] I have added or updated the appropriate tests	
- [ ] I have updated related documentation

#### Bots
- [ ] I have validated that new and updated responses use appropriate [Speak](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-text-to-speech?view=azure-bot-service-3.0) and [InputHint](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-add-input-hints?view=azure-bot-service-3.0) properties to ensure a high-quality speech-first experience
- [ ] I have replicated language model changes across the English, French, Italian, German, Spanish, and Chinese `.lu` files and validated that deployment is successful

#### Deployment Scripts
- [ ] I have replicated my changes in the **Virtual Assistant Template** and **Sample** projects
- [ ] I have replicated my changes in the **Skill Template** and **Sample** projects

2019-07-24 22:03 UTC, Dewain27 commented
@ryanlengel please verify that I linked to the proper location for this... Thx

2019-07-24 23:36 UTC, lzc850612 requested changes

2019-07-24 23:36 UTC, lzc850612 commented on docs/readme.md
> -|[Telemetry](/docs/reference/analytics/telemetrylogging.md)|How to configure a telemetry collection for your Assistant.|
do we still use telemetrylogging.md anywhere else? if not we could remove it.

2019-07-24 23:41 UTC, ryanlengel commented on docs/readme.md
> -|[Telemetry](/docs/reference/analytics/telemetrylogging.md)|How to configure a telemetry collection for your Assistant.|
It's also referenced in /docs/overview/analytics.md which I'm not sure if we need as well.

2019-07-24 23:42 UTC, ryanlengel commented
New documentation location looks correct, I don't think we need the Application Insights doc either. It will get out of date as the SDK updates.

2019-07-25 03:07 UTC, ryanlengel commented on docs/readme.md
> -|[Telemetry](/docs/reference/analytics/telemetrylogging.md)|How to configure a telemetry collection for your Assistant.|
It's also referenced in /docs/overview/analytics.md which should be cleaned up to reflect these changes.

2019-07-25 03:08 UTC, ryanlengel commented
New documentation location looks correct.
I don't think we need the Application Insights doc either, but will defer to @scheyal on that.

2019-07-26 05:46 UTC, darrenj approved these changes

2019-08-07 23:55 UTC, lauren-mills commented
Pulling this into #2071

2019-08-07 23:55 UTC, closed without merging