[Lib] Fallback lib change
microsoft/botframework-solutions pull request #1976
Opened 2019-07-30 07:10 UTC by DingmaomaoBJTU

### Purpose
[Part 1] #1598 Remove "do you want to hear more" type prompts from Skills

### Changes
Simplify lib code per comments

### Tests
*Is this covered by existing tests or new ones? If no, why not?*

### Feature Plan
*Are there any remaining steps or dependencies before this issue can be fully resolved? If so, describe and link to any relevant pull requests or issues.*

### Checklist

#### General
- [ ] I have commented my code, particularly in hard-to-understand areas	
- [ ] I have added or updated the appropriate tests	
- [ ] I have updated related documentation

#### Bots
- [ ] I have validated that new and updated responses use appropriate [Speak](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-text-to-speech?view=azure-bot-service-3.0) and [InputHint](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-add-input-hints?view=azure-bot-service-3.0) properties to ensure a high-quality speech-first experience
- [ ] I have replicated language model changes across the English, French, Italian, German, Spanish, and Chinese `.lu` files and validated that deployment is successful

#### Deployment Scripts
- [ ] I have replicated my changes in the **Virtual Assistant Template** and **Sample** projects
- [ ] I have replicated my changes in the **Skill Template** and **Sample** projects

2019-07-30 21:39 UTC, lzc850612 requested changes

2019-07-30 21:39 UTC, lzc850612 commented on lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Dialogs/RouterDialog.cs
> +                                                if (routerDialogTurnResult.Status == RouterDialogTurnStatus.Restart)
can be merged into one if statement

2019-07-30 21:40 UTC, lzc850612 commented
@lauren-mills  can you take a look at the RouterDialog change? turns out we still need to do something because the SDK will swallow the Empty DialogTurnStatus result so we have to define our own TurnStatus to achieve what we want

2019-07-31 00:55 UTC, darrenj commented on lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/SkillDialog.cs
> +                        result.Result = new RouterDialogTurnResult(RouterDialogTurnStatus.Restart);
We should raise a suggestion on botframework-dotnet to add this state to [DialogTurnStatus](https://docs.microsoft.com/en-us/dotnet/api/microsoft.bot.builder.dialogs.dialogturnstatus?view=botbuilder-dotnet-stable)

2019-07-31 01:17 UTC, lauren-mills approved these changes

2019-07-31 02:18 UTC, DingmaomaoBJTU commented on lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/SkillDialog.cs
> +                        result.Result = new RouterDialogTurnResult(RouterDialogTurnStatus.Restart);
Issue logged~ https://github.com/microsoft/botbuilder-dotnet/issues/2351

2019-07-31 18:02 UTC, lzc850612 requested changes

2019-07-31 18:02 UTC, lzc850612 commented on lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/SkillDialog.cs
> +            if (innerDc.ActiveDialog?.Id == DialogIds.ConfirmPrompt)
let's rename both the variable name and the string of the dialog id to be 'confirmSkillSwitchPrompt' instead of just 'confirmPrompt'

2019-08-01 01:25 UTC, lzc850612 approved these changes

2019-08-01 05:12 UTC, merged