[Calendar] Calendar bot with adaptive SDK only - basic function Preview
microsoft/botframework-solutions pull request #2025
Opened 2019-08-02 09:27 UTC by DingmaomaoBJTU

### Purpose
A calendar skill bot sample with adaptive sdk only (v4.6), with basic function only.

Feature list:
![image](https://user-images.githubusercontent.com/16643193/62360048-9267e300-b54a-11e9-8a69-a74ed59d86d8.png)

![image](https://user-images.githubusercontent.com/16643193/62360082-af9cb180-b54a-11e9-9a5f-a7341ac6cd79.png)

![image](https://user-images.githubusercontent.com/16643193/62360106-bc210a00-b54a-11e9-9e33-91eea9164c1b.png)

![image](https://user-images.githubusercontent.com/16643193/62360151-cb07bc80-b54a-11e9-9d35-703fc3c209df.png)

### Changes
*Are there any changes that need to be called out as significant or particularly difficult to grasp? (Include illustrative screenshots for context if applicable.)*

### Tests
*Is this covered by existing tests or new ones? If no, why not?*

### Feature Plan
*Are there any remaining steps or dependencies before this issue can be fully resolved? If so, describe and link to any relevant pull requests or issues.*

### Checklist

#### General
- [ ] I have commented my code, particularly in hard-to-understand areas	
- [ ] I have added or updated the appropriate tests	
- [ ] I have updated related documentation

#### Bots
- [ ] I have validated that new and updated responses use appropriate [Speak](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-text-to-speech?view=azure-bot-service-3.0) and [InputHint](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-add-input-hints?view=azure-bot-service-3.0) properties to ensure a high-quality speech-first experience
- [ ] I have replicated language model changes across the English, French, Italian, German, Spanish, and Chinese `.lu` files and validated that deployment is successful

#### Deployment Scripts
- [ ] I have replicated my changes in the **Virtual Assistant Template** and **Sample** projects
- [ ] I have replicated my changes in the **Skill Template** and **Sample** projects

2019-08-05 16:26 UTC, lauren-mills approved these changes

2019-08-05 23:02 UTC, lzc850612 requested changes

2019-08-05 23:02 UTC, lzc850612 commented on skills/src/csharp/Skills.sln
> +# Visual Studio 15
Please do not change these. We can't be going back and forth with changes like this.

I'm assuming you're using Visual Studio 2017. Please use Visual Studio 2019 instead.

2019-08-06 10:00 UTC, DingmaomaoBJTU commented on skills/src/csharp/Skills.sln
> +# Visual Studio 15
Sure~ Fixed and will upgrade :grinning: 

---
In reply to: [310824391](https://github.com/microsoft/botframework-solutions/pull/2025#discussion_r310824391) [](ancestors = 310824391)

2019-08-07 19:19 UTC, lzc850612 approved these changes

2019-08-08 03:10 UTC, merged