[Skills] LG support for Email/Calendar/Todo/POI skill
microsoft/botframework-solutions pull request #2061
Opened 2019-08-07 10:49 UTC by KayMKM

### Purpose
*What is the context of this pull request? Why is it being done?*
Support LG in Email/Calendar/Todo/POI skill.
Close #2058 

### Changes
*Are there any changes that need to be called out as significant or particularly difficult to grasp? (Include illustrative screenshots for context if applicable.)*
Replace all responses to LG.

### Tests
*Is this covered by existing tests or new ones? If no, why not?*
Yes

### Feature Plan
*Are there any remaining steps or dependencies before this issue can be fully resolved? If so, describe and link to any relevant pull requests or issues.*
Apply new LG package in future and support multi-language.

### Checklist

#### General
- [x] I have commented my code, particularly in hard-to-understand areas	
- [x] I have added or updated the appropriate tests	
- [ ] I have updated related documentation

#### Bots
- [ ] I have validated that new and updated responses use appropriate [Speak](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-text-to-speech?view=azure-bot-service-3.0) and [InputHint](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-add-input-hints?view=azure-bot-service-3.0) properties to ensure a high-quality speech-first experience
- [ ] I have replicated language model changes across the English, French, Italian, German, Spanish, and Chinese `.lu` files and validated that deployment is successful

#### Deployment Scripts
- [ ] I have replicated my changes in the **Virtual Assistant Template** and **Sample** projects
- [ ] I have replicated my changes in the **Skill Template** and **Sample** projects

2019-08-07 18:21 UTC, lauren-mills commented
This should not be going into master yet. Since LG is slated for ignite, this should be targeting the future branch.

2019-08-08 00:43 UTC, lzc850612 commented
yeah please change the merge branch to future otherwise you've got too many unrelated changes.

2019-08-08 06:23 UTC, KayMKM commented
sorry for choosing the wrong branch. changed to future~

2019-08-08 17:12 UTC, lauren-mills reviewed
Seems like there are some inconsistencies between the implementations between projects. Files like startup.cs, dialogbot.cs, botservices.cs, adapter.cs, and other common files should all look mostly the same so its easier to maintain.

2019-08-08 17:12 UTC, lauren-mills commented on lib/csharp/microsoft.bot.builder.solutions/microsoft.bot.builder.solutions/Testing/DefaultTestAdapter.cs
> +            Use(new AutoSaveStateMiddleware(botStateSet));
We should remove autosavestatemiddleware since its deprecated

2019-08-08 17:12 UTC, lauren-mills commented on skills/src/csharp/calendarskill/calendarskill/Utilities/LGHelper.cs
> +    public class LGHelper
I don't think we should be introducing this extra helper class. If the sdk work is so complicated that we need a helper, we should be raising that as a feature request. Also, its only two lines, so it doesn't seem like we're gaining much by adding it.

2019-08-08 17:12 UTC, lauren-mills commented on skills/src/csharp/calendarskill/calendarskill/Responses/Main/MainDialog.zh-cn.lg
> +��ã�����Calendar Bot���ҿ���Ϊ���ṩ����Ļ��鰲�ţ������һ��������ϸ��Ϣ������Ϊ�㴴���»��顣
This might be a file encoding issue

2019-08-09 02:52 UTC, DingmaomaoBJTU commented on skills/src/csharp/calendarskill/calendarskill/Utilities/LGHelper.cs
> +    public class LGHelper
Yes, We wrap this because LG calling function is in a changing state... Every time it changes, we need to change everywhere. But if we pack it here, we only need to change two lines^_^ So how about we keep this and restore when LG pkg is finally stabilized?

2019-08-09 19:03 UTC, lzc850612 requested changes

2019-08-09 19:03 UTC, lzc850612 commented on lib/csharp/Directory.Build.props
> +    <TreatWarningsAsErrors>False</TreatWarningsAsErrors>
undo this

2019-08-09 19:03 UTC, lzc850612 commented on lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/Microsoft.Bot.Builder.Skills.csproj
> +    <ProjectReference Include="..\..\microsoft.bot.builder.solutions\microsoft.bot.builder.solutions\Microsoft.Bot.Builder.Solutions.csproj" />
you should be referencing the daily build, not the source code directly.

and what feature exactly is that you need from the latest solutions lib?

2019-08-09 19:03 UTC, lzc850612 commented on skills/src/csharp/Skills.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Microsoft.Bot.Builder.Skills", "..\..\..\lib\csharp\microsoft.bot.builder.skills\Microsoft.Bot.Builder.Skills\Microsoft.Bot.Builder.Skills.csproj"
shouldn't be referencing source code

2019-08-09 19:03 UTC, lzc850612 commented on skills/src/csharp/calendarskill/calendarskill/Bots/DialogBot.cs
> +    public class DialogBot<T> : ActivityHandler
what's the reason to change it to ActivityHandler?

2019-08-09 19:03 UTC, lzc850612 commented on skills/src/csharp/calendarskill/calendarskill/CalendarSkill.csproj
> +    <Optimize>false</Optimize>
what's this for?

2019-08-09 19:03 UTC, lzc850612 commented on skills/src/csharp/calendarskill/calendarskill/CalendarSkill.csproj
> +    <PackageReference Include="Microsoft.Bot.Builder.Skills" Version="4.5.1144" />
what's this version 4.5.1144? never seen this

2019-08-09 19:03 UTC, lzc850612 commented on skills/src/csharp/calendarskill/calendarskill/CalendarSkill.csproj
> +    <ProjectReference Include="..\..\..\..\..\lib\csharp\microsoft.bot.builder.skills\Microsoft.Bot.Builder.Skills\Microsoft.Bot.Builder.Skills.csproj" />
shouldn't be referencing source code.

2019-08-09 19:03 UTC, lzc850612 commented on skills/src/csharp/calendarskill/calendarskilltest/Flow/CalendarBotTestBase.cs
> +			Services.AddTransient<ChangeEventStatusDialog>();
please fix indentation

2019-08-09 19:03 UTC, lzc850612 commented on skills/src/csharp/emailskill/emailskill/EmailSkill.csproj
> +    <ProjectReference Include="..\..\..\..\..\lib\csharp\microsoft.bot.builder.skills\Microsoft.Bot.Builder.Skills\Microsoft.Bot.Builder.Skills.csproj" />
shouldn't be referencing source code.

2019-08-09 19:03 UTC, lzc850612 commented on skills/src/csharp/calendarskill/calendarskill/Startup.cs
> +            services.AddTransient<IWhitelistAuthenticationProvider, WhitelistAuthenticationProvider>();
so i haven't implemented the sample to use IWhitelistAuthenticationProvider within a skill. ideally you should be using a settings (json) file to hold the list and your implementation of the interface to be reading from that settings file. this way you can allow caller of the skill by changing the configuration.

2019-08-09 19:03 UTC, lzc850612 commented on skills/src/csharp/calendarskill/calendarskill/Startup.cs
> +            services.AddTransient<IWhitelistAuthenticationProvider, WhitelistAuthenticationProvider>();
let me work on that and then you can follow that change to do this.

2019-08-12 01:12 UTC, DingmaomaoBJTU commented on skills/src/csharp/calendarskill/calendarskill/CalendarSkill.csproj
> +    <ProjectReference Include="..\..\..\..\..\lib\csharp\microsoft.bot.builder.skills\Microsoft.Bot.Builder.Skills\Microsoft.Bot.Builder.Skills.csproj" />
This change is in future branch (so no lib preview package will be built), and we need to update the lib the SDK preview to make LG work. Can we include source code directly in future branch in this case?

2019-08-12 02:41 UTC, KayMKM commented on skills/src/csharp/calendarskill/calendarskill/Bots/DialogBot.cs
> +    public class DialogBot<T> : ActivityHandler
we are using latest daily sdk package. need change to ActivityHandler on that.

2019-08-12 17:58 UTC, lzc850612 commented on skills/src/csharp/calendarskill/calendarskill/CalendarSkill.csproj
> +    <ProjectReference Include="..\..\..\..\..\lib\csharp\microsoft.bot.builder.skills\Microsoft.Bot.Builder.Skills\Microsoft.Bot.Builder.Skills.csproj" />
in short, no.

what is the feature that's required in the latest skills lib that you need for this change?

2019-08-14 08:23 UTC, KayMKM commented on skills/src/csharp/calendarskill/calendarskill/CalendarSkill.csproj
> +    <ProjectReference Include="..\..\..\..\..\lib\csharp\microsoft.bot.builder.skills\Microsoft.Bot.Builder.Skills\Microsoft.Bot.Builder.Skills.csproj" />
we need to use the latest bot framework sdk that support lg. so one of the reasons we updated skills and solutions is to use new bot framework lib. another is update test adapter to fix mock auth issue.

2019-08-14 08:43 UTC, KayMKM commented on skills/src/csharp/calendarskill/calendarskill/CalendarSkill.csproj
> +    <Optimize>false</Optimize>
will remove this change

2019-08-15 09:43 UTC, KayMKM commented on skills/src/csharp/calendarskill/calendarskill/CalendarSkill.csproj
> +    <ProjectReference Include="..\..\..\..\..\lib\csharp\microsoft.bot.builder.skills\Microsoft.Bot.Builder.Skills\Microsoft.Bot.Builder.Skills.csproj" />
There is the PR of libs part: https://github.com/microsoft/botframework-solutions/pull/2123. Once it is merged, we can release a package then reference it in skills.

2019-08-27 05:23 UTC, lzc850612 approved these changes

2019-08-27 05:23 UTC, merged