Add IT Service Management skill
microsoft/botframework-solutions pull request #2078
Opened 2019-08-08 11:25 UTC by xieofxie

### Purpose
*What is the context of this pull request? Why is it being done?*

Related to #931.

**Currently, only the create ticket action is finished and this pr is proposed for fixes about structure design, code style etc. for further development.**

### Changes
*Are there any changes that need to be called out as significant or particularly difficult to grasp? (Include illustrative screenshots for context if applicable.)*

* Add CreateTicketDialog following the flow
* Add IITServiceManagement and related models as a high level abstraction
    * Currently, all defines are following ServiceNow
* Use package **RestSharp** for calling REST api of ServiceNow
    * Which is better? Use class to bind attributes or simply a Dictionary<string, dynamic> for anything possible?

### Tests
*Is this covered by existing tests or new ones? If no, why not?*

Test on Emulator, Teams

### Feature Plan
*Are there any remaining steps or dependencies before this issue can be fully resolved? If so, describe and link to any relevant pull requests or issues.*

#2062 for Generic Oauth 2

### Checklist

#### General
- [ ] I have commented my code, particularly in hard-to-understand areas	
- [ ] I have added or updated the appropriate tests	
- [ ] I have updated related documentation

#### Bots
- [ ] I have validated that new and updated responses use appropriate [Speak](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-text-to-speech?view=azure-bot-service-3.0) and [InputHint](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-add-input-hints?view=azure-bot-service-3.0) properties to ensure a high-quality speech-first experience
- [ ] I have replicated language model changes across the English, French, Italian, German, Spanish, and Chinese `.lu` files and validated that deployment is successful

#### Deployment Scripts
- [ ] I have replicated my changes in the **Virtual Assistant Template** and **Sample** projects
- [ ] I have replicated my changes in the **Skill Template** and **Sample** projects

2019-08-08 18:00 UTC, lauren-mills approved these changes

2019-08-08 18:46 UTC, lzc850612 requested changes

2019-08-08 18:46 UTC, lzc850612 commented on skills/src/csharp/experimental/itsmskill/Connected Services/Application Insights/ConnectedService.json
> +﻿{
this file is probably not needed

2019-08-09 09:52 UTC, xieofxie commented on skills/src/csharp/experimental/itsmskill/Connected Services/Application Insights/ConnectedService.json
> +﻿{
OK, file removed

2019-08-09 09:54 UTC, xieofxie commented
Provide images for flow. Will wait until Oauth issue is released in public package.

2019-08-09 18:50 UTC, lzc850612 approved these changes

2019-08-12 09:52 UTC, xieofxie commented
Add update ticket flow with changes of names and functions to simplify code (but it will definitely expect more in the future).
![Untitled](https://user-images.githubusercontent.com/2876650/62857316-e1bbc980-bd29-11e9-896a-922d265ef977.png)
![Untitled](https://user-images.githubusercontent.com/2876650/62857353-f8622080-bd29-11e9-83d3-f4df38c4de7d.png)

2019-08-13 04:08 UTC, xieofxie commented
* Add show ticket flow
* Add serviceNowGetUserId. User has to setup a scripted REST api

With more actions and tests, the design is changing frequently.. So it is better to review after all is settled.

![Untitled](https://user-images.githubusercontent.com/2876650/62914457-04e68780-bdc3-11e9-8f1f-0da3c2356e1f.png)

2019-08-13 07:12 UTC, xieofxie commented
Add close ticket flow
![Untitled](https://user-images.githubusercontent.com/2876650/62921959-c067e580-bddc-11e9-93f4-f54bea19031a.png)

2019-08-13 09:20 UTC, xieofxie commented
Add search knowledge base action (similar to the one in create)
![Untitled](https://user-images.githubusercontent.com/2876650/62930200-8a336180-bdee-11e9-9341-6e39cddee0a5.png)

2019-08-13 09:24 UTC, xieofxie commented
Since it only supports sending notifications via email/sms/phone push service/service now bot in Slack/Teams, it is not easy to invoke proactive notification in bot (we could use an email to trigger bot, but it is too complex).
https://docs.servicenow.com/bundle/madrid-servicenow-platform/page/administer/notification/reference/notifications.html

2019-08-13 12:22 UTC, xieofxie commented
* Redesign update ticket action (new flow are shown in previous comment)
* AttributePrompt only accepts no
* Use DescriptionAttribute for enum to string

2019-08-15 08:00 UTC, xieofxie commented
* add class GeneralPrompt for next/prev navigation
* add next/prev to show knowledge base and ticket
* show knowledge invoke create ticket if required
![Untitled](https://user-images.githubusercontent.com/2876650/63081258-c0e7b400-bf75-11e9-8f39-4569f5b5e64e.png)

2019-08-15 16:48 UTC, darrenj approved these changes

2019-08-16 03:26 UTC, lzc850612 approved these changes

2019-08-21 06:41 UTC, xieofxie commented
In the latest commit, a SimpleWhitelistAuthenticationProvider is added in startup.cs and experimental.md is updated.
@lzc850612 Please check the usage of SimpleWhitelistAuthenticationProvider.
@ryanlengel What about the flows and designs? Thanks~

2019-08-26 09:36 UTC, xieofxie commented
In commit "[ITSM] add top login prompt, additional sources, TicketState":
* login prompt is required at begin of each root dialog
* additional sources are added and should be removed when published
* add TicketState support like search for closed tickets etc.

In commit "[ITSM] use ticket number instead of id":
* add TicketNumber entity, TicketNumberPrompt to use ticket number instead of sys id. When there are duplicate numbers, errors are returned.

New flows:
![update](https://user-images.githubusercontent.com/2876650/63681167-d12a4980-c827-11e9-9015-3e52166a1143.png)
![close](https://user-images.githubusercontent.com/2876650/63681173-d2f40d00-c827-11e9-98c6-0c8c41420732.png)

In commit "[ITSM] add url and number to knowledge base":
* knowledge base articles also uses number and a button is added to open url

![knowledge](https://user-images.githubusercontent.com/2876650/63681253-ffa82480-c827-11e9-9463-bd7ef59ba470.png)

2019-08-29 20:10 UTC, lzc850612 commented
> In the latest commit, a SimpleWhitelistAuthenticationProvider is added in startup.cs and experimental.md is updated.
> @lzc850612 Please check the usage of SimpleWhitelistAuthenticationProvider.
> @ryanlengel What about the flows and designs? Thanks~

i don't think i saw the code SimpleWhitelistAuthenticationProvider.cs in the PR.

> In the latest commit, a SimpleWhitelistAuthenticationProvider is added in startup.cs and experimental.md is updated.
> @lzc850612 Please check the usage of SimpleWhitelistAuthenticationProvider.
> @ryanlengel What about the flows and designs? Thanks~

2019-08-29 20:11 UTC, lzc850612 requested changes
not seeing the SimpleWhitelistAuthenticationProvider.cs code

2019-08-30 06:51 UTC, xieofxie commented
OK, in the last commit, it is under Utilities.

2019-09-02 15:47 UTC, darrenj requested changes
Deployed the latest build and like the improvements, a few observations which could be part of a new PR so you can merge this and work on changes?

- [ ] This utterance isn't understood and should just show the ticket status `what is the status of INC0010001`
- [ ] Show my tickets prompts for constraints - doesn't feel right in this situation+? Should just show my tickets, not sure users will have many? Filtering could be a suggested action shown if there are more than one page worth of items rather than making the user always provide?
- [ ] When I have just one ticket is asks me if I want to see more!

![image](https://user-images.githubusercontent.com/33519520/64125143-e90e4a00-cda0-11e9-9aa9-521195a1eba2.png)

- [ ] Adaptive Card for a ticket should have a button to close, update and go to that flow
- [ ] Ticket Update doesn't enable you to provide ticket number `INC0010001` on the utterance
- [ ] Change Ticket says there is nothing to update?

![image](https://user-images.githubusercontent.com/33519520/64125288-5c17c080-cda1-11e9-9c62-564aeaaf6b45.png)

2019-09-02 15:47 UTC, darrenj commented on skills/src/csharp/experimental/itsmskill/ITSMSkill.csproj
> +    <PackageReference Include="Microsoft.Bot.Builder.Skills" Version="4.6.0-daily20" />
skill should not be using preview builds of Skills? Do we need to use these?

2019-09-02 15:47 UTC, darrenj commented on docs/_docs/reference/skills/experimental.md
> +* Set up a scripted REST API for current user's sys_id following [this question](https://community.servicenow.com/community?id=community_question&sys_id=52efcb88db1ddb084816f3231f9619c7) and update t
I don't follow what is needed here (and why). Could you update with an example script/steps and explanation of what this is for? Thanks!

2019-09-02 15:47 UTC, darrenj commented on docs/_docs/reference/skills/experimental.md
> +* Add an OAuth Connection in the Settings of Web App Bot named 'ServiceNow' with Service Provider 'Generic Oauth 2'
Clarify no scopes are needed

2019-09-02 15:47 UTC, darrenj commented on docs/_docs/reference/skills/experimental.md
> +    - Authorization URL as https://instance.service-now.com/oauth_auth.do
Emphasise that the user must replace instance with their instance name perhaps use YOUR_INSTANCE_NAME.service-now.com?

2019-09-02 15:47 UTC, darrenj commented on docs/_docs/reference/skills/experimental.md
> +
Click Test Connection to verify

2019-09-02 15:53 UTC, darrenj submitted a review, later dismissed

2019-09-02 15:53 UTC, darrenj commented on skills/src/csharp/experimental/itsmskill/Responses/Knowledge/KnowledgeResponses.json
> +        "text": "Page {Page}. Do you find what you want? \"Go forward/previously\" to navigate.",
previous not previously

2019-09-02 15:53 UTC, darrenj commented on skills/src/csharp/experimental/itsmskill/Responses/Knowledge/KnowledgeResponses.json
> +        "text": "Page {Page} does not contain anything, try \"Go previously\".",
Previous

2019-09-02 15:53 UTC, darrenj commented on skills/src/csharp/experimental/itsmskill/Responses/Knowledge/KnowledgeResponses.json
> +      {
I'm sorry, I can't find any articles. Let me know if I can help in another way.

2019-09-02 15:53 UTC, darrenj commented on skills/src/csharp/experimental/itsmskill/Responses/Main/MainResponses.json
> +        "text": "Welcome to IT Service Managerment skill! You can view, create or resolve tickets here.",
Welcome to the IT Service Management skill...

2019-09-02 15:53 UTC, darrenj commented on skills/src/csharp/experimental/itsmskill/Responses/Shared/SharedResponses.json
> +        "text": "Let me know if you need my help with something else.",
anything else

2019-09-02 15:53 UTC, darrenj commented on skills/src/csharp/experimental/itsmskill/Responses/Shared/SharedResponses.json
> +        "text": "Please input the description:",
Please provide the description

2019-09-02 15:53 UTC, darrenj commented on skills/src/csharp/experimental/itsmskill/Responses/Shared/SharedResponses.json
> +        "text": "Please input the ticket number:",
Please provide the ticket number

2019-09-02 15:53 UTC, darrenj commented on skills/src/csharp/experimental/itsmskill/Responses/Shared/SharedResponses.json
> +        "text": "Sorry, IT service failed due to {Error}.",
Sorry, connecting to the IT Service Management service failed due to {Error}

2019-09-02 15:53 UTC, darrenj commented on skills/src/csharp/experimental/itsmskill/Responses/Ticket/TicketResponses.json
> +        "text": "Page {Page}. Does one of these solve your problem? \"Go forward/previously\" to navigate.",
Do any of these solve your problem? Go forward/previous to navigate

2019-09-02 15:53 UTC, darrenj commented on skills/src/csharp/experimental/itsmskill/Responses/Ticket/TicketResponses.json
> +        "text": "What attribute do you want to set for updating? Or \"No\" for no more attribute.",
Which attribute do you want to update?

2019-09-02 15:53 UTC, darrenj commented on skills/src/csharp/experimental/itsmskill/Responses/Ticket/TicketResponses.json
> +        "text": "You didn't set anything to update. Let me know when you need my help.",
You didn't provide any changes, let me know when..

2019-09-03 02:58 UTC, xieofxie commented on skills/src/csharp/experimental/itsmskill/ITSMSkill.csproj
> +    <PackageReference Include="Microsoft.Bot.Builder.Skills" Version="4.6.0-daily20" />
No, it only needs the updated OAuthProviderExtensions::GetAuthenticationProvider. I am only afraid that mismatch might broken the code..

2019-09-03 03:51 UTC, xieofxie commented
OK, others would be in a separate pr. But what about change request of @lzc850612 ?

2019-09-03 19:36 UTC, lzc850612 commented on skills/src/csharp/experimental/itsmskill/ITSMSkill.csproj
> +    <PackageReference Include="Microsoft.Bot.Builder.Skills" Version="4.6.0-daily20" />
Since this is on the next branch, it's depending on some changes that's currently only in next branch which means it's in the daily build. We can change it to published version when release

2019-09-03 23:06 UTC, lzc850612 approved these changes

2019-09-04 17:07 UTC, lauren-mills approved these changes

2019-09-05 04:02 UTC, merged