Set CallerId in SkillWebSocketTransport
microsoft/botframework-solutions pull request #2138
Opened 2019-08-16 07:30 UTC by xieofxie

### Purpose
*What is the context of this pull request? Why is it being done?*

Close #2137 

### Changes
*Are there any changes that need to be called out as significant or particularly difficult to grasp? (Include illustrative screenshots for context if applicable.)*

Set CallerId in SkillWebSocketTransport instead of SkillDialog.

### Tests
*Is this covered by existing tests or new ones? If no, why not?*

### Feature Plan
*Are there any remaining steps or dependencies before this issue can be fully resolved? If so, describe and link to any relevant pull requests or issues.*

### Checklist

#### General
- [ ] I have commented my code, particularly in hard-to-understand areas	
- [ ] I have added or updated the appropriate tests	
- [ ] I have updated related documentation

#### Bots
- [ ] I have validated that new and updated responses use appropriate [Speak](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-text-to-speech?view=azure-bot-service-3.0) and [InputHint](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-add-input-hints?view=azure-bot-service-3.0) properties to ensure a high-quality speech-first experience
- [ ] I have replicated language model changes across the English, French, Italian, German, Spanish, and Chinese `.lu` files and validated that deployment is successful

#### Deployment Scripts
- [ ] I have replicated my changes in the **Virtual Assistant Template** and **Sample** projects
- [ ] I have replicated my changes in the **Skill Template** and **Sample** projects

2019-08-16 17:07 UTC, lzc850612 commented
why do you want to set the callid in the transport class instead of the SkillDialog? if you set it in the transport class, then in the future any newly added transport would have to do this extra duplicate task. SkillDialog is the single entry into the SkillInvocation so we should set callid in SkillDialog.

2019-08-16 17:07 UTC, lzc850612 requested changes
why do you want to set the callid in the transport class instead of the SkillDialog? if you set it in the transport class, then in the future any newly added transport would have to do this extra duplicate task. SkillDialog is the single entry into the SkillInvocation so we should set callid in SkillDialog.

2019-08-16 18:30 UTC, lzc850612 commented
Just realize that you're right since we have CancelRemoteDialogsAsync calls that are not called by ForwardToSkill calls we need this at a lower level.

2019-08-16 18:31 UTC, lzc850612 approved these changes

2019-08-16 18:31 UTC, lzc850612 commented on lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/SkillDialog.cs
remove the empty line

2019-08-19 02:54 UTC, xieofxie commented on lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/SkillDialog.cs
Removed. I wrote too less in issue..
Just be curious about the purpose of CallerId. It is added too months ago without any usage. And will this modification violates the description *'This field is not intended to be transmitted over the wire'*?

2019-08-19 17:52 UTC, lzc850612 commented on lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/SkillDialog.cs
The caller id is added in the SDK specifically for the skill invocation scenario. Its purpose is to add additional layer of security because the Skill will perform validation between this call id and the one that's included in the JWT token claims. With this additional validation it's harder for malicious attacker to impersonate calling bot as you may be able to tamper with any property in the Activity object, but you can't generate a JWT token with another app id unless you have its password.

2019-08-19 17:53 UTC, lzc850612 commented on lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/SkillDialog.cs
a

2019-08-19 18:54 UTC, ryanisgrig approved these changes

2019-08-20 02:40 UTC, xieofxie commented on lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/SkillDialog.cs
Got it, thanks~

2019-08-20 14:59 UTC, merged