[WIP] Add support for utterance like "my manager" or "his boss"
microsoft/botframework-solutions pull request #2197
Opened 2019-08-23 08:47 UTC by xhr0804

<!--- This repository only accepts pull requests related to open issues, please link the open issue in description below. See https://help.github.com/articles/closing-issues-using-keywords/ to learn about automation. 
close #2183 

### Purpose
When I input "book a meeting with my manager" or "book a meeting with Tom and his boss", the calendar skill can not identify who is "my manager" or "his boss".

The PR can help identify the real Entity of this kind of utterance just like "my manager", and add him as an attendee of the meeting.

### Changes
*Are there any changes that need to be called out as significant or particularly difficult to grasp? (Include illustrative screenshots for context if applicable.)*
The old version can not identify "my manager" or "his boss" as an entity, it works like:
![image](https://user-images.githubusercontent.com/44257569/63579243-bf953780-c5c4-11e9-9698-ccefa5055e24.png)

but now, it works like(MiriamG is my manager):
![image](https://user-images.githubusercontent.com/44257569/63578573-56f98b00-c5c3-11e9-802c-b99c36aec90e.png)

and like(Nestor is Allan's boss):
![image](https://user-images.githubusercontent.com/44257569/63579375-1438b280-c5c5-11e9-853b-554aaf9da56a.png)

### Tests
*Is this covered by existing tests or new ones? If no, why not?*
Test some cases myself.

### Feature Plan
*Are there any remaining steps or dependencies before this issue can be fully resolved? If so, describe and link to any relevant pull requests or issues.*

### Checklist

#### General
- [ ] I have commented my code, particularly in hard-to-understand areas	
- [ ] I have added or updated the appropriate tests	
- [ ] I have updated related documentation

#### Bots
- [ ] I have validated that new and updated responses use appropriate [Speak](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-text-to-speech?view=azure-bot-service-3.0) and [InputHint](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-add-input-hints?view=azure-bot-service-3.0) properties to ensure a high-quality speech-first experience
- [ ] I have replicated language model changes across the English, French, Italian, German, Spanish, and Chinese `.lu` files and validated that deployment is successful

#### Deployment Scripts
- [ ] I have replicated my changes in the **Virtual Assistant Template** and **Sample** projects
- [ ] I have replicated my changes in the **Skill Template** and **Sample** projects

2019-08-28 08:05 UTC, DingmaomaoBJTU commented on skills/src/csharp/calendarskill/calendarskill/Services/GoogleAPI/GooglePeopleService.cs
> +
Change to things like this? otherwise, you need to check whether a PersonModel is empty outside.
public async Task<PersonModel> GetMyManagerAsync()
        {
            return null;
        }

        public async Task<PersonModel> GetManagerAsync(string name)
        {
            return null;
        }

2019-08-28 08:34 UTC, xhr0804 commented on skills/src/csharp/calendarskill/calendarskill/Services/GoogleAPI/GooglePeopleService.cs
> +
fixed the issue

2019-08-28 19:08 UTC, lauren-mills requested changes

2019-08-28 19:08 UTC, lauren-mills commented on skills/src/csharp/calendarskill/calendarskill/Services/CalendarLuis.cs
> +                public InstanceData[] PossecivePronoun;
Small typo: should be possessive instead

2019-08-28 20:36 UTC, lzc850612 submitted a review, later dismissed

2019-08-28 20:36 UTC, lzc850612 commented on skills/src/csharp/calendarskill/calendarskill/Services/CalendarLuis.cs
> +                public InstanceData[] PossecivePronoun;
The *.lu files have the same problem.

2019-08-29 04:23 UTC, xhr0804 commented on skills/src/csharp/calendarskill/calendarskill/Services/CalendarLuis.cs
> +                public InstanceData[] PossecivePronoun;
fixed the problem. It is caused by a mistake of a Chinese translator tool.

2019-08-29 06:02 UTC, DingmaomaoBJTU commented on skills/src/csharp/calendarskill/calendarskill/Dialogs/CalendarSkillDialogBase.cs
> +                            }
Please also add this in other cases.

2019-08-29 06:15 UTC, DingmaomaoBJTU commented on skills/src/csharp/calendarskill/calendarskill/Services/CalendarLuis.cs
> +// Code generated by LUISGen .\Calendar.json -cs Luis.CalendarLuis -o ..\..\..\..\Services\
Code generated by LUISGen.

2019-08-29 06:15 UTC, DingmaomaoBJTU commented on skills/src/csharp/calendarskill/calendarskill/Services/CalendarLuis.cs
> +// Code generated by LUISGen .\Calendar.json -cs Luis.CalendarLuis -o ..\..\..\..\Services\
Remove the others

---
In reply to: [318900473](https://github.com/microsoft/botframework-solutions/pull/2197#discussion_r318900473) [](ancestors = 318900473)

2019-08-29 06:24 UTC, DingmaomaoBJTU commented on skills/src/csharp/calendarskill/calendarskill/Dialogs/CalendarSkillDialogBase.cs
> +                                state.MeetingInfor.ContactInfor.RelatedEntityInfoDict = GetRelatedEntityFromRelationship(entity, luisResult.Text, state.MeetingInfor.ContactInfor.RelatedEntityInfoDict
>state.MeetingInfor.ContactInfor.RelatedEntityInfoDict [](start = 146, length = 53)

You can pass state.MeetingInfor.ContactInfor.RelatedEntityInfoDict into this function and handle it directly. No need to return it back, I guess.

2019-08-29 06:43 UTC, DingmaomaoBJTU commented on skills/src/csharp/calendarskill/calendarskill/Dialogs/CalendarSkillDialogBase.cs
> +                            entities.Add(originalName, new CalendarSkillState.RelatedEntityInfo { PronounType = pronounType, RelationshipName = relationshipName });
>entities.Add [](start = 28, length = 12)

Will it throw when it has the same key?

2019-08-29 07:02 UTC, DingmaomaoBJTU commented on skills/src/csharp/calendarskill/calendarskill/Dialogs/CalendarSkillDialogBase.cs
> +                                state.MeetingInfor.ContactInfor.RelatedEntityInfoDict = GetRelatedEntityFromRelationship(entity, luisResult.Text, state.MeetingInfor.ContactInfor.RelatedEntityInfoDict
You can add an Extension Method to handle the dictionary merge issue.

---
In reply to: [318902732](https://github.com/microsoft/botframework-solutions/pull/2197#discussion_r318902732) [](ancestors = 318902732)

2019-08-29 07:40 UTC, DingmaomaoBJTU commented on skills/src/csharp/calendarskill/calendarskill/Dialogs/FindContactDialog.cs
> +                    if (pronounType == "FirstPerson")
>FirstPerson [](start = 40, length = 11)

Define as const string

2019-08-29 08:59 UTC, DingmaomaoBJTU commented
Add get manage api only support for work account. Please handle the exception for personal account

2019-08-29 09:05 UTC, DingmaomaoBJTU commented
This API need new permission support: User.Read.All . Please add this to docs and scripts.

2019-08-30 08:15 UTC, DingmaomaoBJTU commented
And one more question, do you support analysis relationship name during contact slot filling?

2019-09-02 03:29 UTC, xhr0804 commented on skills/src/csharp/calendarskill/calendarskill/Dialogs/CalendarSkillDialogBase.cs
> +                            }
fixed

2019-09-02 03:34 UTC, xhr0804 commented
> And one more question, do you support analysis relationship name during contact slot filling?

Added this feature~

2019-09-04 17:09 UTC, lauren-mills approved these changes

2019-09-05 00:51 UTC, DingmaomaoBJTU commented
> - `User.ReadBasic.All`  

This can be removed as we add `User.Read.All`

---
Refers to: docs/reference/skills/productivity-calendar.md:121 in 6e408b7. [](commit_id = 6e408b7c5a52d409cb9bf24899661b2bc9bd817f, deletion_comment = False)

2019-09-05 00:52 UTC, DingmaomaoBJTU commented on skills/src/csharp/calendarskill/calendarskill/manifestTemplate.json
> +      "scopes": "User.ReadBasic.All, Calendars.ReadWrite, People.Read, Contacts.Read, User.Read.All"
>User.ReadBasic.All [](start = 17, length = 18)

Remove this.

2019-09-05 01:00 UTC, DingmaomaoBJTU commented on skills/src/csharp/calendarskill/calendarskill/Dialogs/CalendarSkillDialogBase.cs
> +                                state.MeetingInfor.ContactInfor.RelatedEntityInfoDict = GetRelatedEntityFromRelationship(entity, luisResult.Text, state.MeetingInfor.ContactInfor.RelatedEntityInfoDict
>state.MeetingInfor.ContactInfor.RelatedEntityInfoDict = GetRelatedEntityFromRelationship(entity, luisResult.Text, state.MeetingInfor.ContactInfor.RelatedEntityInfoDict); [](start = 32, length = 169)

What I mean is, 1) get related entities from GetRelatedEntityFromRelationship 2) merge outside

You don't need to pass state.MeetingInfor.ContactInfor.RelatedEntityInfoDict into this function.

2019-09-19 08:47 UTC, DingmaomaoBJTU approved these changes

2019-09-19 08:59 UTC, merged