add auth steps before call api
microsoft/botframework-solutions pull request #2382
Opened 2019-09-17 08:41 UTC by KayMKM

### Purpose
Close #2373 

### Changes
add auth steps before api call to avoid token expired exception

### Tests
*Is this covered by existing tests or new ones? If no, why not?*

### Feature Plan
*Are there any remaining steps or dependencies before this issue can be fully resolved? If so, describe and link to any relevant pull requests or issues.*

### Checklist

#### General
- [x] I have commented my code, particularly in hard-to-understand areas	
- [x] I have added or updated the appropriate tests	
- [ ] I have updated related documentation

#### Bots
- [ ] I have validated that new and updated responses use appropriate [Speak](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-text-to-speech?view=azure-bot-service-3.0) and [InputHint](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-add-input-hints?view=azure-bot-service-3.0) properties to ensure a high-quality speech-first experience
- [ ] I have replicated language model changes across the English, French, Italian, German, Spanish, and Chinese `.lu` files and validated that deployment is successful

#### Deployment Scripts
- [ ] I have replicated my changes in the **Virtual Assistant Template** and **Sample** projects
- [ ] I have replicated my changes in the **Skill Template** and **Sample** projects

2019-09-19 08:12 UTC, bobokids approved these changes

2019-09-24 04:43 UTC, darrenj requested changes
This relates to our storage of the token in state which on reflection is something we should stop doing - if we request a token each time we need it (increased overhead I know) then it won't have expired even after a period of time.

Could we prototype that change to understand the change in more detail?

2019-09-26 18:46 UTC, ryanlengel commented
Please rebase against next to capture the refactoring changes

2019-10-21 09:45 UTC, darrenj approved these changes

2019-10-21 09:45 UTC, merged