[Weather] use Latitude & Longitude if possible
microsoft/botframework-solutions pull request #2447
Opened 2019-09-27 04:20 UTC by xieofxie

### Purpose
*What is the context of this pull request? Why is it being done?*

Close #2163

### Changes
*Are there any changes that need to be called out as significant or particularly difficult to grasp? (Include illustrative screenshots for context if applicable.)*

* Samples are removed
* Set Latitude & Longitude from event
  - **Note that event could also be place's name**
* Use Latitude & Longitude if no Geography
  - **Note that Geography precedes Latitude & Longitude**
* Add Service.GetLocationByGeoAsync

![w](https://user-images.githubusercontent.com/2876650/65742034-0d034800-e121-11e9-9690-8f6320a8d6fc.png)

### Tests
*Is this covered by existing tests or new ones? If no, why not?*

### Feature Plan
*Are there any remaining steps or dependencies before this issue can be fully resolved? If so, describe and link to any relevant pull requests or issues.*

### Checklist

#### General
- [ ] I have commented my code, particularly in hard-to-understand areas	
- [ ] I have added or updated the appropriate tests	
- [ ] I have updated related documentation

#### Bots
- [ ] I have validated that new and updated responses use appropriate [Speak](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-text-to-speech?view=azure-bot-service-3.0) and [InputHint](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-add-input-hints?view=azure-bot-service-3.0) properties to ensure a high-quality speech-first experience
- [ ] I have replicated language model changes across the English, French, Italian, German, Spanish, and Chinese `.lu` files and validated that deployment is successful

#### Deployment Scripts
- [ ] I have replicated my changes in the **Virtual Assistant Template** and **Sample** projects
- [ ] I have replicated my changes in the **Skill Template** and **Sample** projects

2019-09-28 03:59 UTC, darrenj approved these changes

2019-09-30 16:16 UTC, ryanisgrig requested changes
The manifest file should reflect a location slot like POI Skill

2019-10-08 02:59 UTC, xieofxie commented
The manifest already contains one for name. Update the utterance

2019-10-09 15:25 UTC, ryanisgrig approved these changes

2019-10-09 15:26 UTC, merged