[Skills] synchronize deploy scripts by templates
microsoft/botframework-solutions pull request #2486
Opened 2019-10-08 04:26 UTC by xieofxie

### Purpose
*What is the context of this pull request? Why is it being done?*

Close #2473

### Changes
*Are there any changes that need to be called out as significant or particularly difficult to grasp? (Include illustrative screenshots for context if applicable.)*

Synchronize all skills' deploy scripts by ones from templates.

Run from root:
``` Powershell
$target = Join-Path "Deployment" "Scripts"

$skillSrc = Join-Path "templates" "Skill-Template" "csharp" "Template" "Skill"
$skillDst = [System.Collections.ArrayList]@(Join-Path "templates" "Skill-Template" "csharp" "Sample" "SkillSample")

$skills = @("calendarskill", "emailskill", "pointofinterestskill", "todoskill")

$expSkills = @("automotiveskill", "bingsearchskill", "eventskill", "hospitalityskill", "itsmskill", "musicskill", "newsskill", "phoneskill", "restaurantbookingskill", "weatherskill")

foreach ($skill in $skills)
{
    $skillDst.Add($(Join-Path "skills" "csharp" $skill)) > $null
}

foreach ($skill in $expSkills)
{
    $skillDst.Add($(Join-Path "skills" "csharp" "experimental" $skill)) > $null
}

foreach ($skill in $skillDst)
{
    Copy-Item $(Join-Path $skillSrc $target "*") -Destination $(Join-Path $skill $target) -Recurse
}

```

### Tests
*Is this covered by existing tests or new ones? If no, why not?*

### Feature Plan
*Are there any remaining steps or dependencies before this issue can be fully resolved? If so, describe and link to any relevant pull requests or issues.*

### Checklist

#### General
- [ ] I have commented my code, particularly in hard-to-understand areas	
- [ ] I have added or updated the appropriate tests	
- [ ] I have updated related documentation

#### Bots
- [ ] I have validated that new and updated responses use appropriate [Speak](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-text-to-speech?view=azure-bot-service-3.0) and [InputHint](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-add-input-hints?view=azure-bot-service-3.0) properties to ensure a high-quality speech-first experience
- [ ] I have replicated language model changes across the English, French, Italian, German, Spanish, and Chinese `.lu` files and validated that deployment is successful

#### Deployment Scripts
- [ ] I have replicated my changes in the **Virtual Assistant Template** and **Sample** projects
- [x] I have replicated my changes in the **Skill Template** and **Sample** projects

2019-10-08 12:48 UTC, darrenj approved these changes
Great automated update script!

2019-10-08 18:11 UTC, lauren-mills requested changes

2019-10-08 18:11 UTC, lauren-mills commented on skills/csharp/emailskill/Deployment/Scripts/deploy_cognitive_models.ps1
> +	[switch] $useDispatch = $false,
This shouldn't need to be hard-coded to false. It is false by default

2019-10-09 02:19 UTC, xieofxie commented on skills/csharp/emailskill/Deployment/Scripts/deploy_cognitive_models.ps1
> +	[switch] $useDispatch = $false,
OK, updated everything~

2019-10-14 16:45 UTC, lauren-mills approved these changes

2019-10-15 01:45 UTC, merged