new lg sdk
microsoft/botframework-solutions pull request #2529
Opened 2019-10-14 15:42 UTC by ssss141414

### Purpose
*What is the context of this pull request? Why is it being done?*
Support LG in Todo Skill.

### Changes
*Are there any changes that need to be called out as significant or particularly difficult to grasp? (Include illustrative screenshots for context if applicable.)*
New LG SDK, mainly about structed lg.

### Tests
*Is this covered by existing tests or new ones? If no, why not?*
No, will complete it soon.

### Feature Plan
*Are there any remaining steps or dependencies before this issue can be fully resolved? If so, describe and link to any relevant pull requests or issues.*

### Checklist

#### General
- [ ] I have commented my code, particularly in hard-to-understand areas	
- [ ] I have added or updated the appropriate tests	
- [ ] I have updated related documentation

#### Bots
- [ ] I have validated that new and updated responses use appropriate [Speak](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-text-to-speech?view=azure-bot-service-3.0) and [InputHint](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-add-input-hints?view=azure-bot-service-3.0) properties to ensure a high-quality speech-first experience
- [ ] I have replicated language model changes across the English, French, Italian, German, Spanish, and Chinese `.lu` files and validated that deployment is successful

#### Deployment Scripts
- [ ] I have replicated my changes in the **Virtual Assistant Template** and **Sample** projects
- [ ] I have replicated my changes in the **Skill Template** and **Sample** projects

2019-10-14 21:18 UTC, bobokids commented
This PR is still in WIP, not ready for review.

2019-11-01 01:45 UTC, DingmaomaoBJTU commented on skills/src/csharp/Skills.sln
> +VisualStudioVersion = 15.0.28307.705
Please keep Version 16 (actually vs2019 is perfered)

2019-11-01 01:56 UTC, DingmaomaoBJTU commented on skills/src/csharp/todoskill/todoskill/Dialogs/ToDoSkillDialogBase.cs
> +            var activity = await new ActivityTemplate("[ShowToDo]").BindToData(turnContext, new
>ShowToDo [](start = 56, length = 8)

Change to variable？

2019-11-01 02:00 UTC, DingmaomaoBJTU commented on skills/src/csharp/todoskill/todoskill/Dialogs/ToDoSkillDialogBase.cs
> +            var activity = await new ActivityTemplate("[ReadMore]").BindToData(turnContext, new
>ReadMore [](start = 56, length = 8)

Same, to variable. We can set a class with veriable first then replace it by auto generated one once the tool is ready.

2019-11-01 02:12 UTC, DingmaomaoBJTU commented on skills/src/csharp/todoskill/todoskill/Responses/DeleteToDo/DeleteToDoTexts.lg
> +- Do you want to delete another task?
Can we simplify it if most item has same Text and Speak? like using "# DeleteAnotherTaskPrompt" only.

2019-11-01 02:42 UTC, DingmaomaoBJTU commented on skills/src/csharp/todoskill/todoskill/Responses/Main/ToDoMainActivities.lg
> +]
For those Text equals Speak, remove speak to simplify code.

2019-11-01 02:53 UTC, DingmaomaoBJTU commented on skills/src/csharp/Skills.sln
> +EndProject
Refer to nuget pkg

2019-11-01 03:25 UTC, KayMKM commented on skills/src/csharp/todoskill/todoskill/Dialogs/ToDoSkillDialogBase.cs
> +            var activity = await ToDoCommonUtil.GetToDoResponseActivity($"[{ToDoSharedResponses.ToDoErrorMessage}]", sc.Context, null);
will ToDoCommonUtil.GetToDoResponseActivity(ToDoSharedResponses.ToDoErrorMessage, sc.Context, null); is better? then add the "[]" in GetToDoResponseActivity function.

2019-11-05 14:39 UTC, ssss141414 commented on skills/src/csharp/todoskill/todoskill/Dialogs/ToDoSkillDialogBase.cs
> +            var activity = await ToDoCommonUtil.GetToDoResponseActivity($"[{ToDoSharedResponses.ToDoErrorMessage}]", sc.Context, null);
Resolved.
Hongyang told me that "[]" will not be support in future. So I use @{TemplateName()} instead, in GetToDoResponseActivity function.

2019-11-05 17:28 UTC, lauren-mills requested changes

2019-11-05 17:28 UTC, lauren-mills commented on lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/Microsoft.Bot.Builder.Skills.csproj
> +    <PackageReference Include="Microsoft.Bot.Builder" Version="4.7.0-preview-191026-1" />
You should be able to use the latest 4.6.0-preview-rc3 nuget now.

2019-11-05 17:28 UTC, lauren-mills commented on skills/src/csharp/todoskill/todoskill/Adapters/DefaultAdapter.cs
> +                var activity = await ToDoCommonUtil.GetToDoResponseActivity(ToDoSharedResponses.ToDoErrorMessage, context, null);
The latest version of the libs should remove the need for this helper utility. Please refer to this PR to see how @darrenj made the changes in the VA template for consistency: https://github.com/microsoft/botframework-solutions/pull/2552/files

2019-11-07 06:47 UTC, ssss141414 commented on skills/src/csharp/todoskill/todoskill/Responses/DeleteToDo/DeleteToDoTexts.lg
> +- Do you want to delete another task?
I removed .Speak items. But I kept .Text suffix for some use.

2019-11-07 07:27 UTC, ssss141414 commented on skills/src/csharp/todoskill/todoskill/Adapters/DefaultAdapter.cs
> +                var activity = await ToDoCommonUtil.GetToDoResponseActivity(ToDoSharedResponses.ToDoErrorMessage, context, null);
Hi, 
1 Darrenj's PR use LocaleTemplateEngineManager to generate activity. What LocaleTemplateEngineManager do is that first add all lg files, and then use a certain locale TemplateEngine to generate activity from certain locale lg files, directly. For example, when locale is zh-cn, it will use a zh-cn TemplateEngine to evaluate MainResponses.zh.cn.lg.
But this won't work in our ToDo/ Email/ Calander skill. Because our lg files are much more complex. They includes some [import], which TemplateEngine can't resolve. We must use ResourceExplore to load all our lg files. Therefore, we can only use new ActivityTemplate(templateName).BindToData(turnContext, data) to realize multi-language feature.
2 I think use CommonUtil is a good design. So that I can concentrate all activity generation processes into CommonUtil function. One this process is changed I only need to modify CommonUtil function. If you think there exists other disadvantage, please tell me.

Thanks a lot!

2019-11-07 08:16 UTC, ssss141414 commented on lib/csharp/microsoft.bot.builder.skills/Microsoft.Bot.Builder.Skills/Microsoft.Bot.Builder.Skills.csproj
> +    <PackageReference Include="Microsoft.Bot.Builder" Version="4.7.0-preview-191026-1" />
sync with next

2019-11-14 05:56 UTC, closed without merging