[Skills] Add spell check for skills
microsoft/botframework-solutions pull request #2687
Opened 2019-11-12 10:18 UTC by DingmaomaoBJTU

### Purpose
Add spell check for skills
Related #2432

### Changes
*Are there any changes that need to be called out as significant or particularly difficult to grasp? (Include illustrative screenshots for context if applicable.)*

### Tests
*Is this covered by existing tests or new ones? If no, why not?*

### Feature Plan
*Are there any remaining steps or dependencies before this issue can be fully resolved? If so, describe and link to any relevant pull requests or issues.*

### Checklist

#### General
- [ ] I have commented my code, particularly in hard-to-understand areas	
- [ ] I have added or updated the appropriate tests	
- [ ] I have updated related documentation

#### Bots
- [ ] I have validated that new and updated responses use appropriate [Speak](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-text-to-speech?view=azure-bot-service-3.0) and [InputHint](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-add-input-hints?view=azure-bot-service-3.0) properties to ensure a high-quality speech-first experience
- [ ] I have replicated language model changes across the English, French, Italian, German, Spanish, and Chinese `.lu` files and validated that deployment is successful

#### Deployment Scripts
- [ ] I have replicated my changes in the **Virtual Assistant Template** and **Sample** projects
- [ ] I have replicated my changes in the **Skill Template** and **Sample** projects

2019-11-12 22:09 UTC, lauren-mills requested changes

2019-11-12 22:09 UTC, lauren-mills commented on skills/csharp/emailskill/Dialogs/EmailSkillDialogBase.cs
> +                string luisResultText = string.IsNullOrEmpty(luisResult.AlteredText) ? luisResult.Text : luisResult.AlteredText;
I have concerns with using the spellcheck result in all scenarios. We've tested this feature in the past and found that sometimes it corrects words incorrectly, which can cause issues for the user. For instance, if the user wants to invite someone to a meeting with a unique name or email address, but spellcheck corrects it, then the contacts API can't find it, there's no way for the user to correct the issue if we always default to the spellcheck result. I think we need to think more about the design here.

2019-11-14 02:04 UTC, DingmaomaoBJTU commented on skills/csharp/emailskill/Dialogs/EmailSkillDialogBase.cs
> +                string luisResultText = string.IsNullOrEmpty(luisResult.AlteredText) ? luisResult.Text : luisResult.AlteredText;
@lauren-mills yes we notice that too. This will impact user name and email address entities mostly which means skills other than calendar and email are OK. But since this feature can be enable/disabled by skill users in setting, how about we add this support in code(as this is a known luis new feature) and talk to luis team about this issue too?

2019-12-02 16:28 UTC, lauren-mills commented on skills/csharp/emailskill/Dialogs/EmailSkillDialogBase.cs
> +                string luisResultText = string.IsNullOrEmpty(luisResult.AlteredText) ? luisResult.Text : luisResult.AlteredText;
@darrenj - thoughts on this?

2019-12-02 17:33 UTC, darrenj commented on skills/csharp/emailskill/Dialogs/EmailSkillDialogBase.cs
> +                string luisResultText = string.IsNullOrEmpty(luisResult.AlteredText) ? luisResult.Text : luisResult.AlteredText;
Agreed - we shouldn't default to this as it causes more issues than it solves for the most part. If we were to add this I would want us to test this more significantly in our test environment and work with LUIS on changes that are required.

2019-12-18 05:06 UTC, bobokids commented
Close this pr for more investigation. User can refer to calendar skill if he/she want to add the spell check feature.

2019-12-18 05:06 UTC, closed without merging