[Calendar/Email] Perf improve by batch retrieving user photo
microsoft/botframework-solutions pull request #2716
Opened 2019-11-15 10:48 UTC by DingmaomaoBJTU

### Purpose
*What is the context of this pull request? Why is it being done?*
Close #2715 Perf improve by batch retrieving user photo

### Changes
Improve email/calendar performance by batch query user photo.

### Tests
*Is this covered by existing tests or new ones? If no, why not?*

### Feature Plan
*Are there any remaining steps or dependencies before this issue can be fully resolved? If so, describe and link to any relevant pull requests or issues.*

### Checklist

#### General
- [ ] I have commented my code, particularly in hard-to-understand areas	
- [ ] I have added or updated the appropriate tests	
- [ ] I have updated related documentation

#### Bots
- [ ] I have validated that new and updated responses use appropriate [Speak](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-text-to-speech?view=azure-bot-service-3.0) and [InputHint](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-add-input-hints?view=azure-bot-service-3.0) properties to ensure a high-quality speech-first experience
- [ ] I have replicated language model changes across the English, French, Italian, German, Spanish, and Chinese `.lu` files and validated that deployment is successful

#### Deployment Scripts
- [ ] I have replicated my changes in the **Virtual Assistant Template** and **Sample** projects
- [ ] I have replicated my changes in the **Skill Template** and **Sample** projects

2019-11-15 11:48 UTC, KayMKM approved these changes

2019-11-15 16:48 UTC, darrenj approved these changes

2019-11-15 16:49 UTC, darrenj requested changes
Could we also take the opportunity to wrap the photo retrieval in an exception handler and use a default image if an error happens. Will help it to be a bit more defensive?

2019-11-18 02:18 UTC, DingmaomaoBJTU commented
> Could we also take the opportunity to wrap the photo retrieval in an exception handler and use a default image if an error happens. Will help it to be a bit more defensive?

@darrenj in calendar/email code, we already had the exception captured and default image returned with "https://ui-avatars.com/api/?name={0}" format. Is it OK or do we need to handle more?

`try
            {
                var url = await service.GetPhotoAsync(email.Address);
                if (!string.IsNullOrEmpty(url))
                {
                    return url;
                }

                // return default value
                return string.Format(AdaptiveCardHelper.DefaultAvatarIconPathFormat, displayName);
            }
            catch (Exception)
            {
                return string.Format(AdaptiveCardHelper.DefaultAvatarIconPathFormat, displayName);
            }`

2019-11-18 21:32 UTC, lzc850612 approved these changes

2019-12-17 16:38 UTC, darrenj approved these changes

2019-12-17 16:38 UTC, darrenj commented
@DingmaomaoBJTU  some conflicts to resolve!

2019-12-17 17:44 UTC, ryanisgrig approved these changes

2019-12-18 04:08 UTC, merged