[Android] support wake word
microsoft/botframework-solutions pull request #2797
Opened 2019-12-10 08:33 UTC by KayMKM

### Purpose
*What is the context of this pull request? Why is it being done?*
support wake word: https://github.com/microsoft/botframework-solutions/issues/1444

### Changes
*Are there any changes that need to be called out as significant or particularly difficult to grasp? (Include illustrative screenshots for context if applicable.)*
1. upgrade speech SDK to 1.8.0
2. add KWS extension
3. enable wake word and settings

known issue: 
only support "computer" as wake word now. because the custom keyword portal can't generate model now:
![image](https://user-images.githubusercontent.com/19773357/70511766-9d6ef780-1b6a-11ea-9df8-97dd5b5d0c8f.png)

### Tests
*Is this covered by existing tests or new ones? If no, why not?*

### Feature Plan
*Are there any remaining steps or dependencies before this issue can be fully resolved? If so, describe and link to any relevant pull requests or issues.*
support "machine" as wake word

### Checklist

#### General
- [ ] I have commented my code, particularly in hard-to-understand areas	
- [ ] I have added or updated the appropriate tests	
- [ ] I have updated related documentation

#### Bots
- [ ] I have validated that new and updated responses use appropriate [Speak](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-text-to-speech?view=azure-bot-service-3.0) and [InputHint](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-add-input-hints?view=azure-bot-service-3.0) properties to ensure a high-quality speech-first experience
- [ ] I have replicated language model changes across the English, French, Italian, German, Spanish, and Chinese `.lu` files and validated that deployment is successful

#### Deployment Scripts
- [ ] I have replicated my changes in the **Virtual Assistant Template** and **Sample** projects
- [ ] I have replicated my changes in the **Skill Template** and **Sample** projects

2019-12-11 00:17 UTC, ryanlengel commented
@KayMKM is the custom keyword portal issue being tracked or do we need to reach out to the correct team?

2019-12-11 00:17 UTC, ryanlengel commented on samples/android/clients/VirtualAssistantClient/directlinespeech/src/main/java/com/microsoft/bot/builder/solutions/directlinespeech/SpeechSdk.java
> +                LogInfo("keywordRecognitaionStarted");
Nit: rename to startKeywordRecognition

2019-12-11 00:18 UTC, ryanlengel commented on samples/android/clients/VirtualAssistantClient/directlinespeech/src/main/java/com/microsoft/bot/builder/solutions/directlinespeech/SpeechSdk.java
> +            LogInfo("stopKeywordListening");
Nit: rename to stopKeywordRecognition

2019-12-11 00:19 UTC, ryanisgrig requested changes
Added logging comments

2019-12-11 02:21 UTC, KayMKM commented
@ryanlengel we need to reach out the correct team. I think we can report this issue to the contact email in custom keyword portal. Or if we can find any related github repo?

2019-12-12 18:41 UTC, ryanlengel commented
I'll send an email to them, thanks!

2019-12-12 18:41 UTC, ryanisgrig approved these changes

2019-12-13 06:12 UTC, bobokids approved these changes

2019-12-13 06:12 UTC, merged