Update VA to use the new SDK QnaMakerDialog
microsoft/botframework-solutions pull request #2809
Opened 2019-12-12 14:33 UTC by darrenj

# QnAMakerDialog Support

Closes #1888 

- Updated Virtual Assistant to use the QnAMakerDialog introduced in SDK R7 which provides Multi-Turn and Active Learning capabilities out of the box. This replaces direct calls to QnAMaker that were provided before
- Added new LG responses for the Active Learning card information to ensure it's localised
- Updates LG response generation in Solutions package to reflect new SDK R7 changes
- Tested with a KB with follow-up prompts
- Obsoleted the `CognitiveModelSet.QnAServices` property as we don't use QnAMaker services, instead we just store the endpoint configuration to enable dialogs to be created. This will nudge people towards a doc item that explains the code change required to an existing VA template.

Note that this will break the Build as it relies on a Solutions lib change. Once PRed we will create a new build and create a new PR referencing the latest bits to avoid the change.

2019-12-12 17:07 UTC, lzc850612 approved these changes

2019-12-13 15:22 UTC, lauren-mills requested changes

2019-12-13 15:22 UTC, lauren-mills commented on docs/_docs/virtual-assistant/handbook/template-updates.md
> +---
We have a whats new section where we can add these notes and have them easier to find for each release. Might fit better there than in the handbook and can have an associated date.

2019-12-13 17:12 UTC, darrenj commented on docs/_docs/virtual-assistant/handbook/template-updates.md
> +---
Fair point, I spoke to @ryanlengel yesterday - any thoughts, happy to move around if we think it's a better place?

2019-12-13 18:08 UTC, ryanlengel commented on docs/_docs/virtual-assistant/handbook/template-updates.md
> +---
I agree with @lauren-mills, it's better to have a single area of docs that would be shared in chronological order.

2019-12-13 18:09 UTC, ryanlengel commented on docs/_docs/virtual-assistant/handbook/template-updates.md
> +---
On the page for this release it can have a section called "Template updates" with this existing doc.

2019-12-16 14:32 UTC, darrenj commented on docs/_docs/virtual-assistant/handbook/template-updates.md
> +---
Moved.

2019-12-16 15:11 UTC, lauren-mills approved these changes
Made some small changes to the metadata of the doc so it will show up in the right place

2019-12-16 15:34 UTC, merged