[Calendar] Meeting Room Booking
microsoft/botframework-solutions pull request #2831
Opened 2019-12-19 04:17 UTC by xhr0804

### Purpose
*What is the context of this pull request? Why is it being done?*

close #934 

### Changes
*Are there any changes that need to be called out as significant or particularly difficult to grasp? (Include illustrative screenshots for context if applicable.)*

implement BookMeetingRoom/CancelMeetingRoom/AddMeeetingRoom/ChangeMeetingRoom and add room feature for the CreateMeeting

**Book a meeting room:**

![image](https://user-images.githubusercontent.com/44257569/71144436-f6204d80-2258-11ea-95a4-449ca4dfc14b.png)
![image](https://user-images.githubusercontent.com/44257569/71144441-f7ea1100-2258-11ea-8056-e3f7a168bcc7.png)

**Cancel meeting room:**

![image](https://user-images.githubusercontent.com/44257569/71144447-020c0f80-2259-11ea-8e9f-3bc087fca4c4.png)

**Add meeting room:**

![image](https://user-images.githubusercontent.com/44257569/71144467-105a2b80-2259-11ea-851c-dddee17b30da.png)

**Change meeting room:**

![image](https://user-images.githubusercontent.com/44257569/71144473-18b26680-2259-11ea-9da6-ca76d39df13d.png)

### Tests
*Is this covered by existing tests or new ones? If no, why not?*

### Feature Plan
*Are there any remaining steps or dependencies before this issue can be fully resolved? If so, describe and link to any relevant pull requests or issues.*
Will provide a tool to import data into cosmosDb/AzureSearch from msgraph.

### Checklist

#### General
- [ ] I have commented my code, particularly in hard-to-understand areas	
- [ ] I have added or updated the appropriate tests	
- [ ] I have updated related documentation

#### Bots
- [ ] I have validated that new and updated responses use appropriate [Speak](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-text-to-speech?view=azure-bot-service-3.0) and [InputHint](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-add-input-hints?view=azure-bot-service-3.0) properties to ensure a high-quality speech-first experience
- [ ] I have replicated language model changes across the English, French, Italian, German, Spanish, and Chinese `.lu` files and validated that deployment is successful

#### Deployment Scripts
- [ ] I have replicated my changes in the **Virtual Assistant Template** and **Sample** projects
- [ ] I have replicated my changes in the **Skill Template** and **Sample** projects

2019-12-19 08:39 UTC, darrenj requested changes
Added some comments below - generally more comments needed to explain some logic and more defensive error handling I think? 

There will be deployment script changes required as well (separate PR would be OK?) to provision azure search instance or enable the user to provide an existing resource (@lauren-mills  could help advise). Configuring cosmosdb/collection too.

In addition the code required to populate cosmosdb with the current meeting rooms should be provided - likely as a sample which we could show working as an azure function executed weekly or something?

Also doc updates to reflect the new scenarios, configuration information, etc.

2019-12-19 08:39 UTC, darrenj commented on skills/csharp/calendarskill/Deployment/Resources/LU/en-us/Calendar.lu
> +- add {ContactName=carlos} to the meeting
Any reason for not using personname pre-built entity? Are these changes run past the LUIS pre-built team?

2019-12-19 08:39 UTC, darrenj commented on skills/csharp/calendarskill/Deployment/Resources/LU/en-us/Calendar.lu
> +- add a room to my {ToTime=3pm} meeting
Assuming that ToTime/etc. entities are those used by other intents in this LUIS model?

2019-12-19 08:39 UTC, darrenj commented on skills/csharp/calendarskill/Deployment/Resources/LU/en-us/Calendar.lu
> +- can i reserve a room in building {Building=5} for a meeting?
As previous comment, have these utterances been reviewed with LUIS team? Just wondering if there are enough variants of meeting room, floor number ?

2019-12-19 08:39 UTC, darrenj commented on skills/csharp/calendarskill/Deployment/Resources/LU/en-us/Calendar.lu
> +- ^does {personName} have time at {FromTime}
This will have to trigger checking a persons time rather than a room?

2019-12-19 08:39 UTC, darrenj commented on skills/csharp/calendarskill/Deployment/Resources/LU/en-us/Calendar.lu
> +$BuildingName:StudioX=
Given these are Microsoft only - do we not need more generic training? We should seek guidance from LUIS team?

2019-12-19 08:39 UTC, darrenj commented on skills/csharp/calendarskill/Dialogs/BookMeetingRoomDialog.cs
> +                DateTime dateNow = TimeConverter.ConvertUtcToUserTime(DateTime.UtcNow, state.GetUserTimeZone());
only initialise when needed within the `if` block below?

2019-12-19 08:39 UTC, darrenj commented on skills/csharp/calendarskill/Dialogs/BookMeetingRoomDialog.cs
> +                if (state.MeetingInfor.MeetingRoom == null)
`MeegingInfo` a typo>

Error handling needed, if meetingroom is a property we always expect to be passed? Otherwise dialog just terminates?

2019-12-19 08:39 UTC, darrenj commented on skills/csharp/calendarskill/Dialogs/MainDialog.cs
> +                            await dc.BeginDialogAsync(nameof(CheckAvailableDialog));
CheckPersonAvailableDialog ?

2019-12-19 08:39 UTC, darrenj commented on skills/csharp/calendarskill/Dialogs/UpdateMeetingRoomDialog.cs
> +                    if (state.MeetingInfor.MeetingRoom == null)
As before, not sure why we end the dialog in this situation - exception handling/logging needed. Validation earlier up the stack to avoid? e.g. Guard statements?

2019-12-19 08:39 UTC, darrenj commented on skills/csharp/calendarskill/Dialogs/UpdateMeetingRoomDialog.cs
> +                    MeetingRoom = meetingRoom ?? "",
Is it valid for meeting room to be null, if not we should have guard statements above - also if you really need it either set to null or `string.Empty`

2019-12-19 08:39 UTC, darrenj commented on skills/csharp/calendarskill/Models/CalendarSkillState.cs
> +            public bool Allday { get; set; } = false;
AllDay ? (casing)

2019-12-19 08:39 UTC, darrenj commented on skills/csharp/calendarskill/Models/DialogOptions/CollectInfoDialogOptions.cs
> +            /// FirstCollect.
Better description to explain what it means?

2019-12-19 08:39 UTC, darrenj commented on skills/csharp/calendarskill/Models/DialogOptions/CollectInfoDialogOptions.cs
> +            Reason = UpdateReason.FirstCollect;
Perhaps simplify with 
```
  public UpdateReason Reason { get; set; } = UpdateReason.FirstCollect;
```

2019-12-19 08:39 UTC, darrenj commented on skills/csharp/calendarskill/Models/DialogOptions/CollectInfoDialogOptions.cs
> +    public class CollectInfoDialogOptions
General comment - not clear what these classes are for so need simple class documentation across the board

2019-12-19 08:39 UTC, darrenj commented on skills/csharp/calendarskill/Prompts/GetRecreateInfoPrompt.cs
> +            regex = new Regex(CalendarCommonStrings.AdjustMeetingRoom);
Any reason for using regex vs LUIS - is this flexible enough for the user?

2019-12-19 08:39 UTC, darrenj commented on skills/csharp/calendarskill/Responses/FindMeetingRoom/FindMeetingRoomDialogActivities.es-es.lg
> +    Text = {NoBuilding.Text()}
Can you please test with the latest 4.7 LG library - this syntax has been deprecated in the latest build and needs to be prefixed with @, for example: `@{NoBuilding.Text()}

2019-12-19 08:39 UTC, darrenj commented on skills/csharp/calendarskill/Services/AzureSearchAPI/AzureSearchClient.cs
> +                    Filter = floorNumber == 0 ? null : "FloorNumber eq " + floorNumber.ToString()
FloorNumber should not be a string literal but a common, shared variable somewhere?

2019-12-19 08:39 UTC, darrenj commented on skills/csharp/calendarskill/Services/AzureSearchAPI/AzureSearchClient.cs
> +                        FloorNumber = int.Parse(item.Document["FloorNumber"].ToString())
We should make this more defensive - what if floor number isn't found in the collection because data isn't available?

2019-12-19 08:39 UTC, darrenj commented on skills/csharp/calendarskill/Services/AzureSearchAPI/AzureSearchClient.cs
> +                        FloorNumber = int.Parse(item.Document["FloorNumber"].ToString())
Some unit tests will help with these types of issues?

2019-12-19 08:39 UTC, darrenj commented on skills/csharp/calendarskill/Services/MSGraphAPI/MSGraphCalendarAPI.cs
> +                    availability.Add(page.AvailabilityView[0] == '0');
Need comments to explain what this is doing? What is there isn't an element in AvailabilityView? (error handling)

2019-12-19 08:39 UTC, darrenj commented on skills/csharp/calendarskill/Utilities/Actions.cs
> +        public const string ConfirmReFindSpecificMeeingRoom = "confirmReFindSpecificMeeingRoom";
Typo? ReFind? MeeingRoom?

2019-12-19 08:53 UTC, xhr0804 commented on skills/csharp/calendarskill/Deployment/Resources/LU/en-us/Calendar.lu
> +- add a room to my {ToTime=3pm} meeting
Yes, we just reuse the ToTime/etc. entities as the other intents like "ChangeCalendarEntry"

2019-12-19 09:40 UTC, xhr0804 commented on skills/csharp/calendarskill/Deployment/Resources/LU/en-us/Calendar.lu
> +- ^does {personName} have time at {FromTime}
The intent "CheckAvailability" includes both MeetingRoom and Person, but we will use the Entity to determine which dialog will be triggered.

2019-12-19 10:56 UTC, xhr0804 commented on skills/csharp/calendarskill/Dialogs/BookMeetingRoomDialog.cs
> +                DateTime dateNow = TimeConverter.ConvertUtcToUserTime(DateTime.UtcNow, state.GetUserTimeZone());
Actually the BookMeetingRoomDialog  just has two steps, first step call FindMeetingRoom, second call the CreateEventDialog.
If we use FindMeetingRoom directly, there will be a confict. Because due to Em's design, CreateEventDialog  will call FindMeetingRoom as a subfloow, while FindMeetingRoom will also call CreateEventDialog as a subflow, this is a conflict. 
So I just create a new Dialog BookMeetingRoom, so that both BookMeetingRoom and CreateEventDialog can call the FindMeetingRoom. This can simplfy the code.

Do you think we should remove the BookMeetingRoomDialog, and merge it into one Dialog?

2020-01-06 03:49 UTC, xhr0804 commented on skills/csharp/calendarskill/Models/DialogOptions/CollectInfoDialogOptions.cs
> +    public class CollectInfoDialogOptions
abandon this option

2020-01-06 05:16 UTC, xhr0804 commented on skills/csharp/calendarskill/Models/DialogOptions/CollectInfoDialogOptions.cs
> +            Reason = UpdateReason.FirstCollect;
fixed, abandon this usage

2020-01-06 05:22 UTC, xhr0804 commented on skills/csharp/calendarskill/Deployment/Resources/LU/en-us/Calendar.lu
> +$BuildingName:StudioX=
removed these internal entities.

2020-01-06 05:25 UTC, xhr0804 commented on skills/csharp/calendarskill/Prompts/GetRecreateInfoPrompt.cs
> +            regex = new Regex(CalendarCommonStrings.AdjustMeetingRoom);
changed to LUIS, I used regex just because it was used in some other part and the previous LUIS model can't support it well.

2020-01-06 09:10 UTC, xhr0804 commented on skills/csharp/calendarskill/Models/CalendarSkillState.cs
> +            public bool Allday { get; set; } = false;
fixed

2020-01-06 10:38 UTC, xhr0804 commented on skills/csharp/calendarskill/Responses/FindMeetingRoom/FindMeetingRoomDialogActivities.es-es.lg
> +    Text = {NoBuilding.Text()}
changed to 4.7

2020-01-06 11:59 UTC, xhr0804 commented on skills/csharp/calendarskill/Deployment/Resources/LU/en-us/Calendar.lu
> +- add {ContactName=carlos} to the meeting
This intent and the utterances are provided by LUIS team. According to LUIS team, the reason for not using pre-built personName entity is that the personName has some limitation. For example, we can not use multiple personNames in one utterance. They will use personName when these limitations are resolved.

2020-01-06 12:04 UTC, xhr0804 commented on skills/csharp/calendarskill/Deployment/Resources/LU/en-us/Calendar.lu
> +- can i reserve a room in building {Building=5} for a meeting?
These utterances are provided by LUIS team, will check with them for the variants.

2020-01-06 15:06 UTC, xhr0804 commented on skills/csharp/calendarskill/Services/MSGraphAPI/MSGraphCalendarAPI.cs
> +                    availability.Add(page.AvailabilityView[0] == '0');
added comments and error handling

2020-01-06 15:08 UTC, xhr0804 commented on skills/csharp/calendarskill/Dialogs/BookMeetingRoomDialog.cs
> +                if (state.MeetingInfor.MeetingRoom == null)
add error handling, when meetingroom==null, throw exception

2020-01-06 15:09 UTC, xhr0804 commented on skills/csharp/calendarskill/Dialogs/UpdateMeetingRoomDialog.cs
> +                    if (state.MeetingInfor.MeetingRoom == null)
added error handling to handle it.

2020-01-06 15:09 UTC, xhr0804 commented on skills/csharp/calendarskill/Dialogs/UpdateMeetingRoomDialog.cs
> +                    MeetingRoom = meetingRoom ?? "",
fixed

2020-01-07 12:49 UTC, xhr0804 commented on skills/csharp/calendarskill/Services/AzureSearchAPI/AzureSearchClient.cs
> +                        FloorNumber = int.Parse(item.Document["FloorNumber"].ToString())
fixed this problem. We will just treat the EmailAddress of meeting room as the required field, while others optional.

2020-01-08 11:39 UTC, xhr0804 commented on skills/csharp/calendarskill/Dialogs/BookMeetingRoomDialog.cs
> +                DateTime dateNow = TimeConverter.ConvertUtcToUserTime(DateTime.UtcNow, state.GetUserTimeZone());
Without info about Time in user's query, we will use "right now" here to initialise.
Or we will collect all the time info in next step FindMeetingRoomDialog.

2020-01-08 11:43 UTC, xhr0804 commented on skills/csharp/calendarskill/Deployment/Resources/LU/en-us/Calendar.lu
> +- add a room to my {ToTime=3pm} meeting
LUIS team already gave us the model for several intents (FindMeetingRoom/CheckAvailability), but not all intents of the flow such as Add(here)/Change/Cancel room. 
They are still working on those intents. We will try to update when it is ready.

2020-01-15 06:27 UTC, xhr0804 commented on skills/csharp/calendarskill/Deployment/Resources/LU/en-us/Calendar.lu
> +- can i reserve a room in building {Building=5} for a meeting?
We have checked the MeetingRoom variants with LUIS team. They have provided more utterances with more variants and some patterns  to recognize meeting room. We have updated this PR with the new luis model.

2020-01-16 09:01 UTC, xhr0804 commented
@darrenj Hi Darren, could you please review the PR again? I've fixed the above comments.

LUIS team has provided more utterences and variants for the FindMeetingRoom, we have added them into our model to improve the recognition accuracy.

I have added a script to support the FindMeetingRoom features, which will create an azure search instance and help populate cosmosdb with the meeting rooms data from MSGraph(including a sign-in step).  User may run this script if they want to use the feature.

Documents are also updated to reflect the new scenarios and the guide to use FindMeetingRoom.

2020-01-20 04:41 UTC, bobokids commented on docs/_docs/skills/samples/calendar.md
> +To use the "FindMeetingRoom" feature, you need follow these steps:
How about we move this part as a standalone section after ###Authentication connection settings?

### Support of search and book a meeting room
Calendar skill provided additional support to search and book a meeting room in the conversation. You can get the meeting room data from the msgraph API and deploy the data to Azure Search Index to provide better search experience.
1. Make sure your meeting room data is complaint with the schema
<Json schema>
2. Configure the setting of your registered app in Azure App Registration portal
        i. Make sure your account have the admin privileges to access your tenant's meeting room data. 
        ii. In API Permissions, add Scopes: **Place.Read.All**
3. Run the following command 
        "./Deployment/Scripts/Enable_findmeetingroom.ps1"
        ### What do these parameters mean?
       <table for parameters>
       When running the script, you will be asked to sign in with your account which can access the meeting room data in the MSGraph.

2020-01-20 05:53 UTC, bobokids commented on docs/_docs/skills/samples/calendar.md
> +|building| Simple entity|
Captical character

2020-01-20 05:54 UTC, bobokids commented on docs/_docs/skills/samples/calendar.md
> +- Find a MeetingRoom
Find a Meeting Room

2020-01-20 10:42 UTC, xhr0804 commented on docs/_docs/skills/samples/calendar.md
> +|building| Simple entity|
fixed

2020-01-20 10:42 UTC, xhr0804 commented on docs/_docs/skills/samples/calendar.md
> +To use the "FindMeetingRoom" feature, you need follow these steps:
sure, updated

2020-01-27 05:08 UTC, darrenj approved these changes

2020-01-27 05:15 UTC, merged