Update Skill Template for new Manifest / SDK GA Changes
microsoft/botframework-solutions pull request #2911
Opened 2020-01-22 19:29 UTC by darrenj

This PR incorporates all of the manual changes tested against Power Virtual Agents enabling a Skill created using this template to work OOB with P-VA and also adds action support.

- New manifest added to wwwroot/manifest folder
- Removed old manifestTemplate.json (therefore a new skill will require the new updates to botskills)

2020-01-22 19:55 UTC, lauren-mills reviewed
Were there any changes that need to be made in the test project template?

2020-01-23 03:22 UTC, lzc850612 requested changes

2020-01-23 03:22 UTC, lzc850612 commented on templates/csharp/Skill/Skill/Bots/DefaultActivityHandler.cs
> +            var activity = turnContext.Activity;
This is done in the latest SkillMiddleware in Microsoft.Bot.Solutions so we don't have to do it here

2020-01-23 03:22 UTC, lzc850612 commented on templates/csharp/Skill/Skill/Controllers/BotController.cs
> +     [Route("api/messages")]
there's an extra space :)

2020-01-23 03:22 UTC, lzc850612 commented on templates/csharp/Skill/Skill/Dialogs/MainDialog.cs
> +        protected override async Task OnEventActivityAsync(DialogContext dc, CancellationToken cancellationToken = default(CancellationToken))
i think the default annotation is the new one. we don't need the (CancellationToken) part.

2020-01-23 03:22 UTC, lzc850612 commented on templates/csharp/Skill/Skill/Dialogs/MainDialog.cs
> +            // Retrieve the prior dialogs result if provided to return on the Skill EndOfConversation event.
so are we still going to put in the new MainDialog by Lauren?

2020-01-23 03:22 UTC, lzc850612 commented on templates/csharp/Skill/Skill/wwwroot/manifest/manifest.json
> +  "$schema": "https://schemas.botframework.com/schemas/skills/skill-manifest-2.0.0.json",
should the version be 2.0.0. or 2.1.0?

2020-01-23 03:29 UTC, darrenj commented
> Were there any changes that need to be made in the test project template?

Yes :-)  Now done!

2020-01-23 03:31 UTC, darrenj commented on templates/csharp/Skill/Skill/Bots/DefaultActivityHandler.cs
> +            var activity = turnContext.Activity;
Removed

2020-01-23 03:32 UTC, darrenj commented on templates/csharp/Skill/Skill/Controllers/BotController.cs
> +     [Route("api/messages")]
removed

2020-01-23 03:35 UTC, darrenj commented on templates/csharp/Skill/Skill/Dialogs/MainDialog.cs
> +        protected override async Task OnEventActivityAsync(DialogContext dc, CancellationToken cancellationToken = default(CancellationToken))
good spot

2020-01-23 03:35 UTC, darrenj commented on templates/csharp/Skill/Skill/Dialogs/MainDialog.cs
> +            // Retrieve the prior dialogs result if provided to return on the Skill EndOfConversation event.
Yes that will follow next

2020-01-23 03:35 UTC, darrenj commented on templates/csharp/Skill/Skill/wwwroot/manifest/manifest.json
> +  "$schema": "https://schemas.botframework.com/schemas/skills/skill-manifest-2.0.0.json",
2.0.0 for now, 2.1.0 later this week / next week

2020-01-23 03:36 UTC, lzc850612 approved these changes

2020-01-23 22:16 UTC, lauren-mills approved these changes

2020-01-23 22:16 UTC, merged