fix calendar bug
microsoft/botframework-solutions pull request #295
Opened 2018-11-13 08:39 UTC by KayMKM

## Description
fix some bugs

## Related Issue
1. state won't clear when update meeting again
2. some ambiguous wordings in update and delete flow
3. only show the start date when show the cross-days meeting
4. when the meeting title contains '"', rendering card will go wrong.
5. won't show the meetings are past when ask "show meetings from 4pm to 9pm"

## Testing Steps
1. input "update my 5pm meeting to 6pm" -> "cancel" -> "update my meeting"
bot should ask for time again
2. input "update my 5pm meeting"(you don't have meeting at 5pm)
bot shouldn't say "It seems there is no event with that name, try again please."
input "update my test meeting"(you don't have meeting that's title is "test")
bot shouldn't say "It seems there is no event at this time, please try again."
3. create a cross-days meeting and ask bot to show it. the adaptive card will show the start date and end date
4. create a meeting with a title contains '"', then ask bot to show it.
5. input "show meetings from 4pm to 9pm"(current time is after 4pm), bot will show all meetings in 4-9pm.

2018-11-13 19:11 UTC, lzc850612 requested changes

2018-11-13 19:11 UTC, lzc850612 commented on solutions/Virtual-Assistant/src/csharp/microsoft.bot.solutions/AdaptiveCards/AdaptiveCardHelper.cs
> +                    escapedTokenStr = escapedTokenStr?.Replace("\"", "\\\"");
can you give us an example on how this change is fixing? seems like you changed the order of these two replacement operations but i don't know how that's going to help.

2018-11-14 02:03 UTC, KayMKM commented on solutions/Virtual-Assistant/src/csharp/microsoft.bot.solutions/AdaptiveCards/AdaptiveCardHelper.cs
> +                    escapedTokenStr = escapedTokenStr?.Replace("\"", "\\\"");
@lzc850612 this is fixing the forth issue: when the meeting title contains '"', rendering card will go wrong. We expect "\\" convert to "\\\\" and "\"" convert to "\\\"". If we didn't change the order, the "\"" will change to "\\\"" first and then convert to "\\\\\"". So we should convert "\\" first.

2018-11-14 02:10 UTC, lzc850612 commented on solutions/Virtual-Assistant/src/csharp/microsoft.bot.solutions/AdaptiveCards/AdaptiveCardHelper.cs
> +                    escapedTokenStr = escapedTokenStr?.Replace("\"", "\\\"");
Ok. Can you please add some comments describing this issue you're saving in the code? this way it's easier for people to understand what you're trying to achieve

2018-11-14 09:55 UTC, KayMKM commented on solutions/Virtual-Assistant/src/csharp/microsoft.bot.solutions/AdaptiveCards/AdaptiveCardHelper.cs
> +                    escapedTokenStr = escapedTokenStr?.Replace("\"", "\\\"");
@lzc850612 comment added

2018-11-14 19:32 UTC, lzc850612 requested changes

2018-11-14 19:32 UTC, lzc850612 commented on solutions/Virtual-Assistant/src/csharp/skills/calendarskill/Models/EventModel.cs
> +                    textString += $"\n{TimeConverter.ConvertUtcToUserTime(eventItem.StartTime, timeZone).ToString("dd-MM-yyyy")} - {TimeConverter.ConvertUtcToUserTime(eventItem.EndTime, timeZone).ToS
define

var userTimeString = $"\n{TimeConverter.ConvertUtcToUserTime(eventItem.StartTime, timeZone)";

and use it in both conditions

and why does the string start with \n ?

2018-11-15 04:30 UTC, KayMKM commented on solutions/Virtual-Assistant/src/csharp/skills/calendarskill/Models/EventModel.cs
> +                    textString += $"\n{TimeConverter.ConvertUtcToUserTime(eventItem.StartTime, timeZone).ToString("dd-MM-yyyy")} - {TimeConverter.ConvertUtcToUserTime(eventItem.EndTime, timeZone).ToS
@lzc850612 had changed in new commit. As designed, we need date in a new line of the card content. But in some case the date won't show. So I linked these strings dynamically here.

2018-11-15 18:18 UTC, lzc850612 approved these changes

2018-11-16 02:10 UTC, merged