[Hopitality] move hungry from chichat to skill
microsoft/botframework-solutions pull request #3051
Opened 2020-02-13 09:29 UTC by xieofxie

### Purpose
*What is the context of this pull request? Why is it being done?*

Close #3044

### Changes
*Are there any changes that need to be called out as significant or particularly difficult to grasp? (Include illustrative screenshots for context if applicable.)*

* move 'If you'd like to take a break and grab something to eat, I'll be here.' from chitchat to hospitality skill's RoomService

Note that other languages are blocked by 
* #3050 
* QnA does not have intents and all are translated which makes it difficult to find the related question

### Tests
*Is this covered by existing tests or new ones? If no, why not?*

### Feature Plan
*Are there any remaining steps or dependencies before this issue can be fully resolved? If so, describe and link to any relevant pull requests or issues.*

### Checklist

#### General
- [ ] I have commented my code, particularly in hard-to-understand areas	
- [ ] I have added or updated the appropriate tests	
- [ ] I have updated related documentation

#### Bots
- [ ] I have validated that new and updated responses use appropriate [Speak](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-text-to-speech?view=azure-bot-service-3.0) and [InputHint](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-add-input-hints?view=azure-bot-service-3.0) properties to ensure a high-quality speech-first experience
- [ ] I have replicated language model changes across the English, French, Italian, German, Spanish, and Chinese `.lu` files and validated that deployment is successful

#### Deployment Scripts
- [ ] I have replicated my changes in the **Virtual Assistant Template** and **Sample** projects
- [ ] I have replicated my changes in the **Skill Template** and **Sample** projects

2020-02-14 20:54 UTC, lzc850612 requested changes

2020-02-14 20:54 UTC, lzc850612 commented on skills/csharp/experimental/hospitalityskill/Deployment/Resources/LU/en-us/Hospitality.lu
> +> from qna_chitchat_Caring # If you'd like to take a break and grab something to eat, I'll be here.
# If you'd like to take a break and grab something to eat, I'll be there. 

should be a separate line.

2020-02-17 02:00 UTC, xieofxie commented on skills/csharp/experimental/hospitalityskill/Deployment/Resources/LU/en-us/Hospitality.lu
> +> from qna_chitchat_Caring # If you'd like to take a break and grab something to eat, I'll be here.
Updated

2020-02-18 21:27 UTC, lzc850612 requested changes

2020-02-18 21:27 UTC, lzc850612 commented on skills/csharp/experimental/hospitalityskill/Deployment/Resources/LU/en-us/Hospitality.lu
> +> below are questions for the following answer from qna_chitchat_Caring
let's put a separate line before line 215 and you should be good to go

2020-02-19 01:58 UTC, xieofxie commented on skills/csharp/experimental/hospitalityskill/Deployment/Resources/LU/en-us/Hospitality.lu
> +> below are questions for the following answer from qna_chitchat_Caring
OK~

2020-02-21 03:59 UTC, lzc850612 approved these changes

2020-02-21 04:09 UTC, bobokids approved these changes

2020-02-21 04:13 UTC, merged