[POI] add action handling code
microsoft/botframework-solutions pull request #3056
Opened 2020-02-14 06:59 UTC by xieofxie

### Purpose
*What is the context of this pull request? Why is it being done?*

2nd step of #2995

### Changes
*Are there any changes that need to be called out as significant or particularly difficult to grasp? (Include illustrative screenshots for context if applicable.)*

* add RouteType for validation since PVA doesn't support enum in json
* add DestinationActionType with logic for ShowRoute attribute
* add action handling code 

### Tests
*Is this covered by existing tests or new ones? If no, why not?*

### Feature Plan
*Are there any remaining steps or dependencies before this issue can be fully resolved? If so, describe and link to any relevant pull requests or issues.*

### Checklist

#### General
- [ ] I have commented my code, particularly in hard-to-understand areas	
- [ ] I have added or updated the appropriate tests	
- [ ] I have updated related documentation

2020-02-24 15:37 UTC, darrenj requested changes

2020-02-24 15:37 UTC, darrenj commented on skills/csharp/pointofinterestskill/Dialogs/MainDialog.cs
> +                                await DigestActoinInput<GetDirectionInput>(stepContext, ev);
Typo - Actioi should be Action

2020-02-24 15:37 UTC, darrenj commented on skills/csharp/pointofinterestskill/Dialogs/PointOfInterestDialogBase.cs
> +                    if (state.DestinationActionType != DestinationActionType.None)
Code comments? What is this code doing?

2020-02-24 15:37 UTC, darrenj commented on skills/csharp/pointofinterestskill/wwwroot/manifest/manifest-1.0.json
> +          "description": "If provided, determine whether show route without prompt."
Indicates whether to show the route without a prompt

2020-02-24 15:37 UTC, darrenj commented on skills/csharp/pointofinterestskill/wwwroot/manifest/manifest-1.0.json
> +          "description": "If provided, determine whether show route without prompt."
Indicates whether to show the route without a prompt

2020-02-24 15:37 UTC, darrenj commented on skills/csharp/pointofinterestskill/wwwroot/manifest/manifest-1.1.json
> +          "description": "If provided, determine whether show route without prompt."
Indicates whether to show the route without a prompt

2020-02-24 15:37 UTC, darrenj commented on skills/csharp/pointofinterestskill/wwwroot/manifest/manifest-1.1.json
> +          "description": "If provided, determine whether show route without prompt."
Indicates whether to show the route without a prompt

2020-02-24 15:37 UTC, darrenj commented on skills/csharp/tests/pointofinterestskill.tests/Flow/Utterances/FindParkingUtterances.cs
> +        public static readonly string FindParkingNearest = "find a nearest parking garage";
find the nearest parking garage

2020-02-24 15:37 UTC, darrenj commented on skills/csharp/tests/pointofinterestskill.tests/Flow/Utterances/FindPointOfInterestUtterances.cs
> +        public static readonly string FindNearestPoi = "find closest poi nearby me";
near me

2020-02-24 15:37 UTC, darrenj commented on skills/csharp/tests/pointofinterestskill.tests/Flow/Utterances/FindPointOfInterestUtterances.cs
> +        public static readonly string FindPharmacy = $"find a {ContextStrings.Pharmacy} nearby me";
nearby, remove the me

2020-02-24 15:37 UTC, darrenj commented on skills/csharp/tests/pointofinterestskill.tests/Flow/Utterances/RouteFromXToYUtterances.cs
> +        public static readonly string GetToNearestPharmacy = $"get directions the nearest {ContextStrings.Pharmacy}";
get directions to the nearest

2020-02-25 02:57 UTC, xieofxie commented on skills/csharp/pointofinterestskill/Dialogs/MainDialog.cs
> +                                await DigestActoinInput<GetDirectionInput>(stepContext, ev);
😱

2020-02-25 02:58 UTC, xieofxie commented on skills/csharp/pointofinterestskill/Dialogs/PointOfInterestDialogBase.cs
> +                    if (state.DestinationActionType != DestinationActionType.None)
Added

2020-02-25 23:22 UTC, lzc850612 approved these changes

2020-02-25 23:23 UTC, merged