[News] change main dialog to waterfall dialog
microsoft/botframework-solutions pull request #3072
Opened 2020-02-18 09:47 UTC by KayMKM

### Purpose
*What is the context of this pull request? Why is it being done?*
Change News skill main dialog to waterfall dialog

### Changes
*Are there any changes that need to be called out as significant or particularly difficult to grasp? (Include illustrative screenshots for context if applicable.)*

### Tests
*Is this covered by existing tests or new ones? If no, why not?*

### Feature Plan
*Are there any remaining steps or dependencies before this issue can be fully resolved? If so, describe and link to any relevant pull requests or issues.*

### Checklist

#### General
- [ ] I have commented my code, particularly in hard-to-understand areas	
- [ ] I have added or updated the appropriate tests	
- [ ] I have updated related documentation

2020-02-18 21:22 UTC, lzc850612 requested changes

2020-02-18 21:22 UTC, lzc850612 commented on skills/csharp/experimental/newsskill/Dialogs/MainDialog.cs
> +                if (state.NewConversation)
this seems like will never be true if the default value of the property is false.

2020-02-19 01:45 UTC, KayMKM commented on skills/csharp/experimental/newsskill/Dialogs/MainDialog.cs
> +                if (state.NewConversation)
fixed. thanks~

2020-02-25 09:51 UTC, bobokids approved these changes

2020-02-26 06:27 UTC, closed without merging