Language Generation TemplateEngine to LGFile changes
microsoft/botframework-solutions pull request #3076
Opened 2020-02-18 19:22 UTC by ryanlengel

### Purpose
*What is the context of this pull request? Why is it being done?*
#3028 

### Changes
*Are there any changes that need to be called out as significant or particularly difficult to grasp? (Include illustrative screenshots for context if applicable.)*
* Update cognitive models to use `QnaMakerEndpoint` property names
* Replace `TemplateEngine` with `LGFile` class in VASample and tests
* Use a single `AllResponses.lg` file that links to other responses

### Tests
*Is this covered by existing tests or new ones? If no, why not?*

### Feature Plan
*Are there any remaining steps or dependencies before this issue can be fully resolved? If so, describe and link to any relevant pull requests or issues.*
* Update build scripts to use updated cognitive models properties
* Apply same changes to Skill Sample
* Apply change in SDK first, when that is good publish a new daily build and PR the VA changes against it

### Checklist

#### General
- [x] I have commented my code, particularly in hard-to-understand areas	
- [x] I have added or updated the appropriate tests	
- [x] I have updated related documentation

2020-02-18 21:19 UTC, lzc850612 requested changes

2020-02-18 21:19 UTC, lzc850612 commented on samples/csharp/assistants/virtual-assistant/VirtualAssistantSample.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Microsoft.Bot.Solutions", "..\..\..\..\sdk\csharp\libraries\microsoft.bot.solutions\Microsoft.Bot.Solutions.csproj", "{7E386078-AB86-4A15-A97C-A63
this is probably by accident?

2020-02-18 21:19 UTC, lzc850612 commented on samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/VirtualAssistantSample.csproj
> +    <ProjectReference Include="..\..\..\..\..\sdk\csharp\libraries\microsoft.bot.solutions\Microsoft.Bot.Solutions.csproj" />
again by accident?

2020-02-18 21:19 UTC, lzc850612 commented on samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/VirtualAssistantSample.csproj
> +    <ProjectReference Include="..\..\..\..\..\sdk\csharp\libraries\microsoft.bot.solutions\Microsoft.Bot.Solutions.csproj" />
seems like you have changes in solutions. should update solutions lib code in a separate PR and get a new build and use that instead of referencing code directly.

2020-02-18 21:19 UTC, lzc850612 commented on samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Startup.cs
> +            var templateFile = "AllResponses";
what's the thinking behind grouping all responses together?

2020-02-18 22:10 UTC, ryanlengel commented on samples/csharp/assistants/virtual-assistant/VirtualAssistantSample.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Microsoft.Bot.Solutions", "..\..\..\..\sdk\csharp\libraries\microsoft.bot.solutions\Microsoft.Bot.Solutions.csproj", "{7E386078-AB86-4A15-A97C-A63
Explained in PR description, I won't wrap this up before going OOF so someone needs to pick it up from here :)

2020-02-18 22:10 UTC, ryanlengel commented on samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/VirtualAssistantSample.csproj
> +    <ProjectReference Include="..\..\..\..\..\sdk\csharp\libraries\microsoft.bot.solutions\Microsoft.Bot.Solutions.csproj" />
Explained in PR description, I won't wrap this up before going OOF so someone needs to pick it up from here :)

2020-02-18 22:11 UTC, ryanlengel commented on samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Startup.cs
> +            var templateFile = "AllResponses";
Explained in PR description; linking to external files in a single LG File will allow developers to make no-code changes if response content needs to be altered. This also seemed like the ideal solution given how LGFile usage differs from the previous TemplateEngine.

2020-02-18 23:02 UTC, lzc850612 commented on samples/csharp/assistants/virtual-assistant/VirtualAssistantSample.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Microsoft.Bot.Solutions", "..\..\..\..\sdk\csharp\libraries\microsoft.bot.solutions\Microsoft.Bot.Solutions.csproj", "{7E386078-AB86-4A15-A97C-A63
got it

2020-02-18 23:17 UTC, lzc850612 commented on samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/VirtualAssistantSample.csproj
> +    <ProjectReference Include="..\..\..\..\..\sdk\csharp\libraries\microsoft.bot.solutions\Microsoft.Bot.Solutions.csproj" />
Got it. I'll help get this change in.

2020-02-20 17:33 UTC, lzc850612 approved these changes

2020-02-20 22:47 UTC, lauren-mills approved these changes

2020-02-20 22:52 UTC, merged