[VA] handle SuppressCompletionMessage
microsoft/botframework-solutions pull request #3129
Opened 2020-03-02 08:13 UTC by xieofxie

### Purpose
*What is the context of this pull request? Why is it being done?*

Close #3115

### Changes
*Are there any changes that need to be called out as significant or particularly difficult to grasp? (Include illustrative screenshots for context if applicable.)*

Suppress before text prompt.

### Tests
*Is this covered by existing tests or new ones? If no, why not?*

No QnA tests now.

### Feature Plan
*Are there any remaining steps or dependencies before this issue can be fully resolved? If so, describe and link to any relevant pull requests or issues.*

### Checklist

#### General
- [ ] I have commented my code, particularly in hard-to-understand areas	
- [ ] I have added or updated the appropriate tests	
- [ ] I have updated related documentation

2020-03-12 10:49 UTC, darrenj requested changes

2020-03-12 10:49 UTC, darrenj commented on samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Dialogs/MainDialog.cs
> +                promptOptions.Prompt = null;
Why not just skip the prompt being created rathe than setting to null?

2020-03-12 10:49 UTC, darrenj commented on samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Dialogs/MainDialog.cs
> +                promptOptions.Prompt = null;
@lauren-mills

2020-03-12 20:31 UTC, lauren-mills requested changes

2020-03-12 20:31 UTC, lauren-mills commented on samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Dialogs/MainDialog.cs
> +                promptOptions.Prompt = null;
Can you try returning EndOfTurn here instead of setting the prompt to null? It should indicate that the dialog stack is waiting for the next user input, without having to set the prompt to null. Just want to make sure the next user message is correctly routed to the RouteStep.

2020-03-13 04:36 UTC, xieofxie commented on samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Dialogs/MainDialog.cs
> +                promptOptions.Prompt = null;
my fault, I didn't think carefully..

2020-03-13 04:39 UTC, xieofxie commented on samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Dialogs/MainDialog.cs
> +                promptOptions.Prompt = null;
I prefer to use TextPrompt to indicate we want text here. EndOfTurn is a bit obscure. Thanks

2020-03-13 18:28 UTC, lzc850612 approved these changes

2020-03-13 18:29 UTC, lauren-mills approved these changes

2020-03-15 10:26 UTC, darrenj approved these changes

2020-03-15 10:26 UTC, merged