Fix email detail read and localization issue
microsoft/botframework-solutions pull request #313
Opened 2018-11-16 12:08 UTC by DingmaomaoBJTU

## Description
Fix email detail read and localization issue

## Related Issue
Email template parts are hardcoded instead of localized #163

## Testing Steps
1. Make a zh-cn bot and check the localization string.
2. Use voice input to make sure details are all read out.

2018-11-16 15:13 UTC, darrenj approved these changes

2018-11-16 19:33 UTC, lzc850612 requested changes

2018-11-16 19:33 UTC, lzc850612 commented on solutions/Virtual-Assistant/src/csharp/microsoft.bot.solutions/Middleware/SetLocaleMiddleware.cs
> +            CommonStrings.Culture = cultureInfo;
CommonStrings has the embedded ResourceManager that can retrieve the strings based on CurrentCulture of the thread. You don't have to override it for it to work.

2018-11-16 19:33 UTC, lzc850612 commented on solutions/Virtual-Assistant/src/csharp/skills/emailskill/Dialogs/ForwardEmail/ForwardEmailDialog.cs
> +                    var nameListString = CommonStrings.To + $"{state.Recipients.FirstOrDefault()?.EmailAddress.Name}";
So this is probably not the best way to do this. We should add resources in the resx files like:

en.resx: EmailToTemplate: "To: {0}"
zh.resx: EmailToTemplate: "发送至： {0}"

The reason we should do this is because we cannot make the assumption that it's always going to be the equivalent of 'To' on the left and then the name. In different languages they could be in different orders. There's also RTL (right to left e.g. Arabic) scenarios so it's better to implement this way.

2018-11-16 19:33 UTC, lzc850612 commented on solutions/Virtual-Assistant/src/csharp/microsoft.bot.solutions/Middleware/SetLocaleMiddleware.cs
> +            CommonStrings.Culture = cultureInfo;
This needs to be reflected on all the related changes you made across this PR, we shouldn't have anything that's doing the string concatenation when we can achieve that in resource string template.

2018-11-19 06:17 UTC, feich-ms commented on solutions/Virtual-Assistant/src/csharp/skills/emailskill/Util/SpeakHelper.cs
> +        private static string ToSpeechEmailSummaryString(WaterfallStepContext sc, Message message)
>WaterfallStepContext sc [](start = 57, length = 23)

Where is 'sc' used?

2018-11-19 11:33 UTC, DingmaomaoBJTU commented on solutions/Virtual-Assistant/src/csharp/skills/emailskill/Dialogs/ForwardEmail/ForwardEmailDialog.cs
> +                    var nameListString = CommonStrings.To + $"{state.Recipients.FirstOrDefault()?.EmailAddress.Name}";
Good suggestion! Fixed all resources~

---
In reply to: [234319043](https://github.com/Microsoft/AI/pull/313#discussion_r234319043) [](ancestors = 234319043)

2018-11-19 11:37 UTC, DingmaomaoBJTU commented on solutions/Virtual-Assistant/src/csharp/microsoft.bot.solutions/Middleware/SetLocaleMiddleware.cs
> +            CommonStrings.Culture = cultureInfo;
Got it, thanks!

---
In reply to: [234318194](https://github.com/Microsoft/AI/pull/313#discussion_r234318194) [](ancestors = 234318194)

2018-11-19 11:37 UTC, DingmaomaoBJTU commented on solutions/Virtual-Assistant/src/csharp/microsoft.bot.solutions/Middleware/SetLocaleMiddleware.cs
> +            CommonStrings.Culture = cultureInfo;
Thank you so much! Fixed~~

---
In reply to: [234320481](https://github.com/Microsoft/AI/pull/313#discussion_r234320481) [](ancestors = 234320481)

2018-11-19 11:40 UTC, DingmaomaoBJTU commented on solutions/Virtual-Assistant/src/csharp/skills/emailskill/Util/SpeakHelper.cs
> +        private static string ToSpeechEmailSummaryString(WaterfallStepContext sc, Message message)
Good catch!! Thanks~ Fixed~ #Resolved

2018-11-19 11:47 UTC, feich-ms approved these changes
:shipit:

2018-11-19 18:54 UTC, lzc850612 requested changes

2018-11-19 18:54 UTC, lzc850612 commented on solutions/Virtual-Assistant/src/csharp/microsoft.bot.solutions/Extensions/ListEx.cs
> +﻿using Microsoft.Bot.Solutions.Resources;
put the Microsoft.Bot.Solutions.Resources namespace using statements lower than the system ones

2018-11-19 18:54 UTC, lzc850612 commented on solutions/Virtual-Assistant/src/csharp/skills/emailskill/Util/DisplayHelper.cs
> +using System.Threading.Tasks;
system usings come first

2018-11-20 00:21 UTC, lzc850612 approved these changes

2018-11-20 02:28 UTC, merged