Chitchat as fallback
microsoft/botframework-solutions pull request #3291
Opened 2020-04-16 23:40 UTC by taicchoumsft

Fixes [#3233](https://github.com/microsoft/botframework-solutions/issues/3233)
### Purpose
LUIS has a tendency to overfit on training data. Our personality datasets tend be very big, and once introduced at the dispatch level, tends to cause dispatch to be biased towards the chitchat intent. 

This PR moves chitchat out of dispatch, and calls the chitchat kb only after skills, faq and other intents are evaluated, and a user-adjustable threshold is met.

### Changes
*Are there any changes that need to be called out as significant or particularly difficult to grasp? (Include illustrative screenshots for context if applicable.)*
The suggested threshold and conditionals are heuristics.  Might have to be adjusted after some testing.

### Tests
*Is this covered by existing tests or new ones? If no, why not?*
 \-

### Feature Plan
*Are there any remaining steps or dependencies before this issue can be fully resolved? If so, describe and link to any relevant pull requests or issues.*
 \-

### Checklist

#### General
- [x] I have commented my code, particularly in hard-to-understand areas	
- [ ] I have added or updated the appropriate tests	
- [ ] I have updated related documentation

2020-04-17 18:22 UTC, peterinnesmsft commented on samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Dialogs/MainDialog.cs
> +            else if (dispatchIntent == DispatchLuis.Intent.None)
>else [](start = 12, length = 4)

You can ditch this else - entering into this block will return, so no need to have an else statement.

2020-04-17 18:22 UTC, peterinnesmsft commented on samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Dialogs/MainDialog.cs
> +            else if (dispatchIntent == DispatchLuis.Intent.l_General)
>else [](start = 12, length = 4)

This one can also be ditched.

2020-04-17 18:29 UTC, peterinnesmsft commented
I would naively assume that these changes need to be made in the templates as well? Also do we need to do this for Skills?

2020-04-17 18:51 UTC, ryanlengel commented on samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Dialogs/MainDialog.cs
> +                var generalResult = stepContext.Context.TurnState.Get<GeneralLuis>(StateProperties.GeneralResult);
The GeneralResult is how l_General scored in the Dispatch app correct?

2020-04-17 18:51 UTC, ryanlengel commented on samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Dialogs/MainDialog.cs
> +                var generalResult = stepContext.Context.TurnState.Get<GeneralLuis>(StateProperties.GeneralResult);
Or GeneralResult is the score in the General LUIS app?

2020-04-17 19:06 UTC, ryanlengel commented on samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Dialogs/MainDialog.cs
> +            if (IsSkillIntent(dispatchIntent))
`IsSkillIIntent` is called before the `ShouldBeginChitChatDialog`, why does it need to be checked here?

2020-04-17 19:19 UTC, taicchoumsft commented on samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Dialogs/MainDialog.cs
> +            if (IsSkillIntent(dispatchIntent))
Yes, skill intent and many others are checked before we reach this point - this is added just in case we change the flow of dialogs. Will remove if you feel this is unncessary.

---
In reply to: [410416659](https://github.com/microsoft/botframework-solutions/pull/3291#discussion_r410416659) [](ancestors = 410416659)

2020-04-17 19:22 UTC, taicchoumsft commented on samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Dialogs/MainDialog.cs
> +                var generalResult = stepContext.Context.TurnState.Get<GeneralLuis>(StateProperties.GeneralResult);
GeneralResult is the score in the General LUIS app.  What was found during testing was that dispatch might score a dispatch level intent as general with very high confidence.  But if we pass the same intent to the General LUIS app, the score is significantly lower.

2020-04-17 19:27 UTC, taicchoumsft commented
Discussed this with Patrick yesterday, and he mentioned templates is generated from sample when we roll out new vsix templates.  No changes needed here. For skills, they do not have chitchat at all, so this is a VA level only change. 

---
In reply to: [615398125](https://github.com/microsoft/botframework-solutions/pull/3291#issuecomment-615398125) [](ancestors = 615398125)

2020-04-20 21:31 UTC, lzc850612 commented on samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Dialogs/MainDialog.cs
> +            if (IsSkillIntent(dispatchIntent))
yeah i think we should remove it as judging by the name of this function it shouldn't care about SkillIntent.

2020-04-20 21:40 UTC, lzc850612 requested changes

2020-04-20 21:40 UTC, lzc850612 commented on samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Dialogs/MainDialog.cs
> +        private bool ShouldBeginChitChatDialog(WaterfallStepContext stepContext, DispatchLuis.Intent dispatchIntent, double dispatchScore, double threshold = 0.5)
to make the code more robust, if you want to make the threshold as a parameter, be sure to check if threshold is within the range of 0 to 1.0

2020-04-20 21:42 UTC, lzc850612 commented
If you are making the change to by default disable ChitChat intent, should we remove q_ChitChat from DispatchLuis.cs? @lauren-mills what do you think?

2020-04-20 22:31 UTC, lzc850612 approved these changes

2020-04-21 22:57 UTC, pavolum approved these changes

2020-04-22 09:22 UTC, darrenj commented
Great for testing this and getting it done. @Batta32 - Could we take this change into typescript VA please ahead of our release?

2020-04-22 09:22 UTC, merged

2020-04-22 09:24 UTC, darrenj commented
@peterinnesmsft @taicchoumsft For our release docs we should have a set of steps for customers to follow with existing VAs to adopt this change. e.g:

- dispatch remove
- dispatch refresh
- change code
- Update deployment scripts (link to existing docs for this)