Pavolum/telephony changes
microsoft/botframework-solutions pull request #3299
Opened 2020-04-21 23:22 UTC by pavolum

### Purpose
*What is the context of this pull request? Why is it being done?*
Adding the following components needed to support telephony channel out of the box
- Added code to ignore blank message activities from DirectLineSpeech channel within activityHandler for both speech and VA
- Added code to grab speak values from attachments if the activity does not have a text or speak value and the attachment has a speak value
- Changes voice for speech scenarios to more human like neural voice
- Added speak values to HeroCard attachment types

2020-04-22 09:26 UTC, darrenj requested changes
Looks like Jessa has been deprecated in favour of Aria - as per [this](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/language-support#neural-voices). Could we take this opportunity to replace all instances of jessa with Aria and quickly validate?

2020-04-22 17:22 UTC, pavolum commented
> Looks like Jessa has been deprecated in favour of Aria - as per [this](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/language-support#neural-voices). Could we take this opportunity to replace all instances of jessa with Aria and quickly validate?

I saw that deprecation message before and tried loads of different ways but no matter what, when I switch it to Aria the bot does not speak and I get no meaningful error messages. I am going to follow up with Egor and Autumn and see if they have any suggestions.

2020-04-22 17:36 UTC, pavolum commented
> Looks like Jessa has been deprecated in favour of Aria - as per [this](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/language-support#neural-voices). Could we take this opportunity to replace all instances of jessa with Aria and quickly validate?

This is why I should reach out to others before spending loads of time trying to debug something that gives no error messages... I was just advised that Neural voices are not supported in all data centers. Here is a doc showing where it is supported: https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/regions#standard-and-neural-voices

This explains why my attempts to switch to the neural voices led to the bot not talking at all. 

Since we can't guarantee which region folks deploy VAs to, we will need to stick with standard voices in the template, I am going to keep the change to the Jessa24kRUS voice since I feel it sounds more human like then the previous one we had.

2020-04-22 17:40 UTC, ryanlengel commented
> > Looks like Jessa has been deprecated in favour of Aria - as per [this](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/language-support#neural-voices). Could we take this opportunity to replace all instances of jessa with Aria and quickly validate?
> 
> This is why I should reach out to others before spending loads of time trying to debug something that gives no error messages... I was just advised that Neural voices are not supported in all data centers. Here is a doc showing where it is supported: https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/regions#standard-and-neural-voices
> 
> This explains why my attempts to switch to the neural voices led to the bot not talking at all.
> 
> Since we can't guarantee which region folks deploy VAs to, we will need to stick with standard voices in the template, I am going to keep the change to the Jessa24kRUS voice since I feel it sounds more human like then the previous one we had.

I think that voice change makes sense for the template. FYI this will reflect on the test environments so if we want a neural voice for demos this is another differentiator we have to account for.

2020-04-22 19:14 UTC, taicchoumsft commented on sdk/csharp/libraries/microsoft.bot.solutions/Middleware/SetSpeakMiddleware.cs
> +                    var contentObj = (JObject)attachmentContent;
>(JObject)attachmentContent [](start = 37, length = 26)

minor nit: `attachmentContent as JObject` may be more C#-ish.  Then you can remove the `typeof` check above.

2020-04-22 20:20 UTC, pavolum commented on sdk/csharp/libraries/microsoft.bot.solutions/Middleware/SetSpeakMiddleware.cs
> +                    var contentObj = (JObject)attachmentContent;
Im not sure if Attachment.content will always be a JObject. The attachment class dictates it is of type Object so maybe there are scenarios in which is not a JObject. Changing the way I cast is fine, but removing the typeof check might be dangerous, right? Unless im missing something.

2020-04-22 20:41 UTC, taicchoumsft commented on sdk/csharp/libraries/microsoft.bot.solutions/Middleware/SetSpeakMiddleware.cs
> +                    var contentObj = (JObject)attachmentContent;
The `as` operator tries to convert the object to the type you requested, if the conversion is not possible, it returns `null`.  Since you do a null check right below, you should be fine removing the `typeof` check. 

---
In reply to: [413301899](https://github.com/microsoft/botframework-solutions/pull/3299#discussion_r413301899) [](ancestors = 413301899)

2020-04-22 21:30 UTC, taicchoumsft approved these changes
:shipit:

2020-04-22 21:32 UTC, taicchoumsft commented on sdk/csharp/libraries/microsoft.bot.solutions/Middleware/SetSpeakMiddleware.cs
> +                    return contentObj["speak"]?.ToString();
>contentObj [](start = 27, length = 10)

question: Not sure if `speak` is also optional... in that case it might be safer to check that too - `contentObj?["speak"]?.ToString();`

2020-04-22 21:34 UTC, taicchoumsft commented on sdk/csharp/libraries/microsoft.bot.solutions/Middleware/SetSpeakMiddleware.cs
> +                    return contentObj["speak"]?.ToString();
>contentObj [](start = 27, length = 10)

Actually it looks like the null check for `contentObj` should be - `contentObj?["speak"]?.ToString()`.

2020-04-23 18:51 UTC, pavolum commented on sdk/csharp/libraries/microsoft.bot.solutions/Middleware/SetSpeakMiddleware.cs
> +                    return contentObj["speak"]?.ToString();
Ahh I see, with this null check then the removal of getType makes sense

2020-04-29 18:45 UTC, peterinnesmsft commented on samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Bots/DefaultActivityHandler.cs
> +            // directline speech occasionally sends empty message activities that should be ignored
>// directline speech occasionally sends empty message activities that should be ignored [](start = 12, length = 87)

This seems weird. Do we know DL Speech does this?

2020-04-29 18:49 UTC, peterinnesmsft commented on samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Responses/MainResponses.lg
> +- This can be used to display information to help your user interact with your bot.
>bot [](start = 79, length = 3)

To be consistent with the tile and general naming, change bot to Virtual Assistant?

2020-04-29 18:57 UTC, lzc850612 commented on samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Bots/DefaultActivityHandler.cs
> +            // directline speech occasionally sends empty message activities that should be ignored
i think i've run into this as well. It'd be good to follow up with DL Speech folks to see why this is the case. It could be that there's some bug in DL Speech

2020-04-29 18:58 UTC, lzc850612 requested changes

2020-04-29 18:58 UTC, lzc850612 commented on sdk/csharp/libraries/microsoft.bot.solutions/Middleware/SetSpeakMiddleware.cs
> +                var attachmentContent = activity.Attachments[0].Content;
what's the scenario that has attachment content for text and speech response?

2020-04-29 18:59 UTC, peterinnesmsft commented on sdk/csharp/libraries/microsoft.bot.solutions/Middleware/SetSpeakMiddleware.cs
> +                    var contentObj = (JObject)attachmentContent;
I think you can actually further simplify a little based on improvements to the `is` keyword since C# 7.0. I would need to double-check the behavior, but I *think* you could write as:

`if (activity.Attachments.Count > 0)
{
    if (activity.Attachments[0].Content is JObject contentObj)
    {
        return contentObj["speak"]?.ToString();
    }
}`

---
In reply to: [413314558](https://github.com/microsoft/botframework-solutions/pull/3299#discussion_r413314558) [](ancestors = 413314558,413301899)

2020-04-29 18:59 UTC, peterinnesmsft approved these changes
:shipit:

2020-04-29 19:02 UTC, darrenj approved these changes

2020-04-29 19:09 UTC, pavolum commented on sdk/csharp/libraries/microsoft.bot.solutions/Middleware/SetSpeakMiddleware.cs
> +                var attachmentContent = activity.Attachments[0].Content;
In our core VA this scenario exists with the help card, onboarding card and escalation card. These scenarios are activities that have no speak or text value but do have attachments with a speak or text value. At current state, nothing would render in a pure speech channel. With this change they would work. 

There were a few options to handle this. I believe this is the best. Instead of changing the root activity in the above scenarios to have speak values, grabbing the speak value from the first attachment ensures all existing VAs work without having to add speak value for all the VAs we support (enterprise, hospitality, skills, etc.). I also think the logic makes sense for general VA development. It ensure speak values of attachments are not ignored in speech scenarios and are instead used as a back up if a speak/test value does not exist on the root activity.

2020-04-29 19:17 UTC, lzc850612 requested changes

2020-04-29 19:17 UTC, lzc850612 commented on sdk/csharp/libraries/microsoft.bot.solutions/Middleware/SetSpeakMiddleware.cs
> +                    return contentObj?["speak"]?.ToString();
i think this would barf if contentObj doesn't have a 'speak' key, even if you have the ? operator after it. probably gonna be 'given key does not exist' or something like it. you need to explicitly check if contentObj has 'speak' key.

2020-04-30 17:00 UTC, pavolum commented on samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Bots/DefaultActivityHandler.cs
> +            // directline speech occasionally sends empty message activities that should be ignored
Ill figure out who to alert and will spin up an email thread with them

2020-04-30 17:18 UTC, pavolum commented on sdk/csharp/libraries/microsoft.bot.solutions/Middleware/SetSpeakMiddleware.cs
> +                    return contentObj?["speak"]?.ToString();
I tested that edge case and if it does not have the speak key then it contentObj?["speak"]?.ToString(); returns null.

I thought it would be an issue as well when Tai suggested this but tested it and sure enough he was right :)

2020-04-30 17:20 UTC, lzc850612 approved these changes

2020-04-30 17:21 UTC, merged