Optimize email flow
microsoft/botframework-solutions pull request #340
Opened 2018-11-21 08:30 UTC by DingmaomaoBJTU

## Description
Optimize email flow
1. Enable 'ReadMore' flow to current ShowEmail/SendEmail/ForwardEmail flow.
2. Enable 'ReadMore' flow to current recipient select step.
3. Fix some bugs related to next/previous page for email list and contact

## Related Issue
Add read more support for email and recipient list #339

## Testing Steps
For email list read more:
1. User: what is my emails?
2. Bot: show list of [6] emails, read out first [3] one
3. User: read more
4: Bot: show the rest of [3] emails, and read them out
5. User: read more
6: Bot:  show next page - list of [6] emails, read out first [3] one

For recipient list read more:
1. User: send an email to qiong
2. Bot: show list of [6] contacts, read out first [3] one
3. User: read more
4: Bot: show the rest of [3] contacts, and read them out
5. User: read more
6: Bot:  show next page - list of [6] contacts, read out first [3] one

The display number [6] and read number [3] is configurable.

2018-11-23 05:59 UTC, feich-ms commented on solutions/Virtual-Assistant/src/csharp/assistant/appsettings.json
> +        "maxDisplaySize": "6"
Where are there two parameters are used?

2018-11-23 06:01 UTC, feich-ms commented on solutions/Virtual-Assistant/src/csharp/microsoft.bot.solutions/Util/CommonUtil.cs
> +        public static readonly int MaxReadSize = 3;
I think it is not needed to limit the size here. It should be up to the users.

2018-11-23 06:28 UTC, feich-ms commented on solutions/Virtual-Assistant/src/csharp/microsoft.bot.solutions/Util/CommonUtil.cs
> +        }
I think we should move this to the function of parsing lu entities.

2018-11-26 06:04 UTC, feich-ms commented on solutions/Virtual-Assistant/src/csharp/assistant/appsettings.json
> +        "maxDisplaySize": "6"
I think we should remove 'max' from the parameter names here.

2018-11-26 07:34 UTC, feich-ms approved these changes

2018-11-28 07:28 UTC, DingmaomaoBJTU commented on solutions/Virtual-Assistant/src/csharp/assistant/appsettings.json
> +        "maxDisplaySize": "6"
Good suggestion! Fixed, thanks!~

2018-11-28 09:26 UTC, darrenj requested changes
- Should ConfigData.cs not be within the Email skill rather than bot.solutions, not sure it's shared?
- As per other PR feedback from Lauren, looks like the changes to CommonStrings are only used by the email skill and not shared, we should place this into the Email commonstrings resource file?

2018-11-29 03:25 UTC, lzc850612 requested changes

2018-11-29 03:25 UTC, lzc850612 commented on solutions/Virtual-Assistant/src/csharp/microsoft.bot.solutions/Data/ConfigData.cs
> +        public static int MaxReadSize
no good comes out of static properties. You can either use the settings from skillconfig directly in wherever needed, or make this a singleton so you can easily mock it when testing.

2018-11-29 07:21 UTC, DingmaomaoBJTU commented
@darrenj These strings I just added are shared ones, and calendar skill is waiting to use them. So I will still keep them in common~ And for ConfigData.cs, it can be shared, and I will make it singleton to ensure better experience~

2018-11-29 08:26 UTC, DingmaomaoBJTU commented on solutions/Virtual-Assistant/src/csharp/microsoft.bot.solutions/Data/ConfigData.cs
> +        public static int MaxReadSize
Make this a singleton~ Thanks!

2018-11-29 22:20 UTC, lzc850612 approved these changes

2018-11-30 13:18 UTC, darrenj approved these changes

2018-11-30 13:19 UTC, darrenj commented
@DingmaomaoBJTU Looks like there is a build failure, can you resolve before merging please?

2018-12-01 01:49 UTC, DingmaomaoBJTU commented
@darrenj Sure, fixed! Sorry for that~~

2018-12-01 01:52 UTC, merged