Update ToDo patterns in dispatch.lu
microsoft/botframework-solutions pull request #342
Opened 2018-11-21 09:29 UTC by feich-ms

Update ToDo patterns in dispatch.lu
## Description
Update ToDo patterns in dispatch.lu

## Related Issue
#51 

## Testing Steps

## Checklist
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated the appropriate unit tests
- [ ] I have updated related documentation

If this contains changes that needs to be replicated between the Enterprise Template <-> Virtual Assistant
- [ ] A duplicate issue is filed to track future  work.

If you have updated responses or `.lu` files:
- [ ] All languages have been updated
- [ ] You have tested deployment with your new models

2018-11-27 17:59 UTC, lauren-mills requested changes

2018-11-27 17:59 UTC, lauren-mills commented on solutions/Virtual-Assistant/src/csharp/assistant/CognitiveModels/LUIS/zh-hans/dispatch.lu
> +- [l_Calendar](../../../../skills/calendarskill/CognitiveModels/LUIS/zh-hans/calendar.lu#ChangeCalendarEntry)
This folder has changed from "zh-hans" to "zh" in the latest LU bug fix

2018-11-27 17:59 UTC, lauren-mills commented on solutions/Virtual-Assistant/src/csharp/assistant/CognitiveModels/LUIS/it/dispatch.lu
> +- aggiungere un'attività al negozio  {ShopContent}
You'll probably have conflicts with master now. It looks good, but just make sure there are no duplicates in the updated files. You can use this powershell script to see if there are any dupes:

```
Get-Content <file_name.lu> | Group-Object | Where-Object { $_.Count -gt 1 } | Select -ExpandProperty Name
```

2018-11-27 17:59 UTC, lauren-mills commented on solutions/Virtual-Assistant/src/csharp/assistant/DeploymentScripts/zh-hans/update_zh.bat
> +call ludown parse toluis --in %0\..\..\..\CognitiveModels\LUIS\zh-hans\dispatch.lu -o %0\..\..\..\DeploymentScripts\zh-hans --out dispatch.luis -n Dispatch -i Dispatch
The latest in master should fix this issue and have added culture for each file

2018-11-28 11:25 UTC, feich-ms commented
@lauren-mills Close this PR due to merge chaos and create a new one here https://github.com/Microsoft/AI/pull/364. Please review that one.

2018-11-28 11:25 UTC, closed without merging

2018-11-28 11:29 UTC, feich-ms commented on solutions/Virtual-Assistant/src/csharp/assistant/CognitiveModels/LUIS/it/dispatch.lu
> +- aggiungere un'attività al negozio  {ShopContent}
Tested and no duplicated patterns are there.

2018-11-28 11:30 UTC, feich-ms commented on solutions/Virtual-Assistant/src/csharp/assistant/CognitiveModels/LUIS/zh-hans/dispatch.lu
> +- [l_Calendar](../../../../skills/calendarskill/CognitiveModels/LUIS/zh-hans/calendar.lu#ChangeCalendarEntry)
yes, have removed the folder of zh-hans. Please see PR #364

2018-11-28 11:45 UTC, feich-ms commented on solutions/Virtual-Assistant/src/csharp/assistant/CognitiveModels/LUIS/it/dispatch.lu
> +- aggiungere un'attività al negozio  {ShopContent}
Please see PR #364

2018-11-28 11:45 UTC, feich-ms commented on solutions/Virtual-Assistant/src/csharp/assistant/DeploymentScripts/zh-hans/update_zh.bat
> +call ludown parse toluis --in %0\..\..\..\CognitiveModels\LUIS\zh-hans\dispatch.lu -o %0\..\..\..\DeploymentScripts\zh-hans --out dispatch.luis -n Dispatch -i Dispatch
yes, thx. Please see PR #364