[TypeScript][Skill] Add Functional Tests
microsoft/botframework-solutions pull request #3542
Opened 2020-07-08 17:45 UTC by Batta32

Related to #3290 

### Purpose
*What is the context of this pull request? Why is it being done?*
There is no functional test applied for Skill in TypeScript.

### Changes
*Are there any changes that need to be called out as significant or particularly difficult to grasp? (Include illustrative screenshots for context if applicable.)*
- Copy and adapt C# Skill functional test as the responses' length between C# and TS are different
- Add yml file for the TypeScript Skill

### Tests
*Is this covered by existing tests or new ones? If no, why not?*
\-

### Feature Plan
*Are there any remaining steps or dependencies before this issue can be fully resolved? If so, describe and link to any relevant pull requests or issues.*
\-

### Checklist

#### General
- [ ] I have commented my code, particularly in hard-to-understand areas	
- [X] I have added or updated the appropriate tests	
- [X] I have updated related documentation

2020-08-13 17:12 UTC, lzc850612 approved these changes

2020-11-17 00:14 UTC, peterinnesmsft requested changes
Let's take a look at the test implementation and tweak it a little. I'd also like to better understand the periodic errors that are initially returned by a TypeScript bot, and fix that correctly rather than work around the issues in the test.

2020-11-17 00:14 UTC, peterinnesmsft commented on templates/typescript/samples/sample-skill/functional-tests/SkillSample.FunctionalTests/DirectLineClientTests.cs
> +        private static readonly string TestName = "Jane Doe";
Use const instead of static readonly

2020-11-17 00:14 UTC, peterinnesmsft commented on templates/typescript/samples/sample-skill/functional-tests/SkillSample.FunctionalTests/DirectLineClientTests.cs
> +        private static string _directLineSecret = string.Empty;
Do these need to be static? If there's no particular need for these to be static, I would just make them regular instance member variables.

2020-11-17 00:14 UTC, peterinnesmsft commented on templates/typescript/samples/sample-skill/functional-tests/SkillSample.FunctionalTests/DirectLineClientTests.cs
> +        [TestInitialize]
This logic looks like it only needs to be performed once, but using [TestInitialize] means it gets executed at the start of each test. Did you mean to use [ClassInitialize] instead?

2020-11-17 00:14 UTC, peterinnesmsft commented on templates/typescript/samples/sample-skill/functional-tests/SkillSample.FunctionalTests/DirectLineClientTests.cs
> +            if (string.IsNullOrWhiteSpace(_directLineSecret) || string.IsNullOrWhiteSpace(_botId))
Isn't this always going to inherently be true that we need to pull in environment variables? Not sure I understand the value of this check.

2020-11-17 00:14 UTC, peterinnesmsft commented on templates/typescript/samples/sample-skill/functional-tests/SkillSample.FunctionalTests/DirectLineClientTests.cs
> +                    Assert.Inconclusive("Environment variable 'DIRECTLINE' not found.");
Avoid using an Assert for this. Throw an ArgumentNullException instead. I would also just fold this logic into a ClassInitialize function rather than have a separate function.

2020-11-17 00:14 UTC, peterinnesmsft commented on templates/typescript/samples/sample-skill/functional-tests/SkillSample.FunctionalTests/DirectLineClientTests.cs
> +                var path = CultureInfo.CurrentUICulture.Name.ToLower() == "en-us" ?
Use String.Equals(..., ..., StringComparison.OrdinalIgnoreCase) instead.

2020-11-17 00:14 UTC, peterinnesmsft commented on templates/typescript/samples/sample-skill/functional-tests/SkillSample.FunctionalTests/DirectLineClientTests.cs
> +                    Path.Combine(".", "Responses", $"AllResponses.{CultureInfo.CurrentUICulture.Name.ToLower()}.lg");
Store in a local variable rather than perform twice?

2020-11-17 00:14 UTC, peterinnesmsft commented on templates/typescript/samples/sample-skill/functional-tests/SkillSample.FunctionalTests/DirectLineClientTests.cs
> +            if (responses.Count == 3)
I'm struggling to understand what the purpose of this check is for. Is this to handle for specific locales?

2020-11-17 00:14 UTC, peterinnesmsft commented on templates/typescript/samples/sample-skill/functional-tests/SkillSample.FunctionalTests/DirectLineClientTests.cs
> +        private static async Task<Conversation> StartBotConversationAsync()
Do we really need a function for this? It feels a little unnecessary given that it's not simply wrapping the call to the client - it doesn't really save anything.

2020-11-17 00:14 UTC, peterinnesmsft commented on templates/typescript/samples/sample-skill/functional-tests/SkillSample.FunctionalTests/DirectLineClientTests.cs
> +            var allFirstPromptTextVariations = AllResponsesTemplates.ExpandTemplate("FirstPromptText");
This is being generated in the test method. Any reason not to pass what's computed there into here? Otherwise you run the risk of code going out of sync.

2020-11-17 00:14 UTC, peterinnesmsft commented on templates/typescript/samples/sample-skill/functional-tests/SkillSample.FunctionalTests/DirectLineClientTests.cs
> +                // In some TypeScript cases the first element is an allFirstPromptTextVariations' text which is an error, so we repeat the request.
Why are we getting an error? If there is periodically an error occurring, then we should fix it so that this behavior is consistent, no?

2020-11-17 00:14 UTC, peterinnesmsft commented on templates/typescript/samples/sample-skill/functional-tests/SkillSample.FunctionalTests/DirectLineClientTests.cs
> +                    // Wait for ten second before polling the bot again.
Injecting arbitrary delays like this is not generally a good idea. What are we trying to accomplish here?

2020-11-17 00:14 UTC, peterinnesmsft commented on templates/typescript/samples/sample-skill/functional-tests/SkillSample.FunctionalTests/DirectLineClientTests.cs
> +                             where x.From.Id == _botId
Linq statements are a little slow in performance. Use Linq extension methods instead, e.g.:

List<Activity> botResponses = activitySet.Activities
    .Where(a => string.Equals(_botId, a.From?.Id, StringComparison.OrdinalIgnoreCase))
    .ToList();

2020-11-17 00:14 UTC, peterinnesmsft commented on templates/typescript/samples/sample-skill/functional-tests/SkillSample.FunctionalTests/DirectLineClientTests.cs
> +            if (activities.Any())
This is a bad usage of Any. Any should be used to determine presence of items that match one or more criteria in a collection. If you are simply checking to see whether the collection is empty, check Count/Length == 0.

That said, performing ToList on the IEnumerable is a relatively trivial thing to do here, so performing the above code in my previous suggestion should be fine.

2020-11-17 00:14 UTC, peterinnesmsft commented on templates/typescript/samples/sample-skill/functional-tests/SkillSample.FunctionalTests/DirectLineClientTests.cs
> +            string watermark = null;
Watermark isn't being used - remove.

2020-11-17 00:14 UTC, peterinnesmsft commented on templates/typescript/samples/sample-skill/functional-tests/SkillSample.FunctionalTests/DirectLineClientTests.cs
> +            // Poll the bot for replies once per second.
Remove this comment - polling occurs outside of this function so it's confusing for this this be located here.

2020-11-17 00:14 UTC, peterinnesmsft commented on templates/typescript/samples/sample-skill/functional-tests/SkillSample.FunctionalTests/DirectLineClientTests.cs
> +        /// Polls the bot continuously until it gets a response.
Again, this function is really just retrieving activities for the conversation. It's not polling itself.

2020-11-17 00:14 UTC, peterinnesmsft commented on templates/typescript/samples/sample-skill/functional-tests/SkillSample.FunctionalTests/DirectLineClientTests.cs
> +                             where x.From.Id == _botId
Although, is there anything that would cause the bot ID to not match? Do we need to actually need to do this check?

2020-11-17 12:54 UTC, Batta32 commented
Thanks @peterinnesmsft, we will review the entire test implementation.

We converted this PR to draft and as soon as it's ready we will move it to be reviewed again.

2020-11-27 18:34 UTC, Batta32 commented
@peterinnesmsft - we already applied the requested feedback.

The next week we will validate the changes in order to confirm that the Functional Test with the TypeScript Skill are working as expected.

Feel free to add the necessary feedback!

2020-12-04 18:29 UTC, Batta32 commented
Hi @peterinnesmsft, we successfully **validated** the changes running the functional test in a pipeline created by the yml. The PR is ready to add any further review or merge.

We will be applying the same feedback for the PR #3463 and PR #3602.

![image](https://user-images.githubusercontent.com/11904023/101200632-56182b80-3645-11eb-9bde-16c69c8d0a08.png)

2021-06-02 18:03 UTC, lauren-mills commented
Closing - outdated

2021-06-02 18:03 UTC, closed without merging