[C#][Bot-Solutions] Add System.Obsolete in the LuisService implementation of BotSettingsBase
microsoft/botframework-solutions pull request #3618
Opened 2020-08-13 20:23 UTC by Batta32

Solves #3617

### Purpose
*What is the context of this pull request? Why is it being done?*
With the new [botbuilder@4.10.0-rc1](https://botbuilder.myget.org/feed/botbuilder-v4-dotnet-daily/package/nuget/Microsoft.Bot.Builder/4.10.0-rc1) packages, the LuisService class has been deprecated so Bot-Solutions doesn't build as it runs into a _"LuisService is obsolete: This class is deprecated"_ error.

### Changes
*Are there any changes that need to be called out as significant or particularly difficult to grasp? (Include illustrative screenshots for context if applicable.)*
We added the `[System.Obsolete]` tag to fix the deprecation error, so that Bot-Solutions builds.

### Tests
*Is this covered by existing tests or new ones? If no, why not?*
We tested the C# solutions, after apply this fix, manually and worked as expected.

_Fix applied_
![image](https://user-images.githubusercontent.com/37625424/90182771-dbbb5700-dd88-11ea-9049-1b7b96877f0d.png)

_Successfully communication in Emulator_
![image](https://user-images.githubusercontent.com/37625424/90182840-eece2700-dd88-11ea-96f4-93e89f6fea72.png)

### Feature Plan
*Are there any remaining steps or dependencies before this issue can be fully resolved? If so, describe and link to any relevant pull requests or issues.*
\-

### Checklist

#### General
- [ ] I have commented my code, particularly in hard-to-understand areas	
- [ ] I have added or updated the appropriate tests	
- [ ] I have updated related documentation

2020-08-13 22:36 UTC, peterinnesmsft commented
Hey @Batta32, I'm not sure the right path forward on this one is to mark these properties as obsolete. I'm assuming we are still ultimately need these in the current Virtual Assistant. If there's an alternative to LuisService that we are intended to be using, then I think we should figure out what that is. Let's discuss and we can figure out a path forward with the SDK team.

2020-08-13 22:36 UTC, peterinnesmsft requested changes
Let's talk to the SDK team first - would like to understand if there is an intended alternative to LuisService if it's been marked as deprecated in the SDK.

2020-08-14 12:13 UTC, Batta32 commented
@peterinnesmsft - Sure! At the meantime, I'll change this PR to draft and we will review another alternatives with the team 😊.

2020-08-19 21:01 UTC, Batta32 commented
@peterinnesmsft - we finished doing the rehome of the used services of `Microsoft.Bot.Configuration` to `Microsoft.Bot.Solutions` . We will move this PR ready to be merged!

2020-09-01 01:24 UTC, peterinnesmsft approved these changes

2020-09-01 20:35 UTC, lauren-mills requested changes

2020-09-01 20:35 UTC, lauren-mills commented on sdk/csharp/libraries/microsoft.bot.solutions/Services/ConnectedService.cs
> +        public virtual void Decrypt(string secret)
We can simplify these classes by removing the encrypt/decrypt methods. We really only need the properties of the different services now.

2020-09-02 14:23 UTC, Batta32 commented on sdk/csharp/libraries/microsoft.bot.solutions/Services/ConnectedService.cs
> +        public virtual void Decrypt(string secret)
Thanks @lauren-mills, we already removed the `encrypt/decrypt` methods.

2020-09-02 17:10 UTC, lauren-mills approved these changes

2021-06-02 18:29 UTC, merged