[Documentation] Update /overview/virtual-assistant-template/ and fix broken links
microsoft/botframework-solutions pull request #3680
Opened 2020-10-09 12:43 UTC by Batta32

Solve #3672

### Purpose
*What is the context of this pull request? Why is it being done?*
The [/overview/virtual-assistant-template/](https://microsoft.github.io/botframework-solutions/overview/virtual-assistant-template/) has broken links and is outdated.

### Changes
*Are there any changes that need to be called out as significant or particularly difficult to grasp? (Include illustrative screenshots for context if applicable.)*
- Fix broken links
- Update documentation with the new version of the Virtual Assistant Template/Sample

### Tests
*Is this covered by existing tests or new ones? If no, why not?*

![image](https://user-images.githubusercontent.com/11904023/95482776-dcc1cc80-0964-11eb-867c-d5f82c952219.png)

![image](https://user-images.githubusercontent.com/11904023/95483056-27dbdf80-0965-11eb-8791-c42025d806b2.png)

![image](https://user-images.githubusercontent.com/11904023/95484044-5c9c6680-0966-11eb-8c69-6758cfacc3ed.png)

### Feature Plan
*Are there any remaining steps or dependencies before this issue can be fully resolved? If so, describe and link to any relevant pull requests or issues.*

### Checklist

#### General
- [ ] I have commented my code, particularly in hard-to-understand areas	
- [ ] I have added or updated the appropriate tests	
- [X] I have updated related documentation

2020-10-16 20:12 UTC, peterinnesmsft approved these changes

2020-10-19 16:50 UTC, ryanlengel requested changes

2020-10-19 16:50 UTC, ryanlengel commented on docs/_docs/overview/virtual-assistant-template.md
> +> Cancel, Confirm, Escalate, ExtrackName, FinishTask, GoBack, Help, Logout, None, ReadAloud, Reject, Repeat, SelectAny, SelectItem, SelectNone, ShowNext, ShowPrevious, StartOver, Stop
Should be ExtractName?

2020-10-19 17:00 UTC, ryanlengel approved these changes

2020-10-19 17:00 UTC, Batta32 commented on docs/_docs/overview/virtual-assistant-template.md
> +> Cancel, Confirm, Escalate, ExtrackName, FinishTask, GoBack, Help, Logout, None, ReadAloud, Reject, Repeat, SelectAny, SelectItem, SelectNone, ShowNext, ShowPrevious, StartOver, Stop
Thanks @ryanlengel for noticing the typo. We already fixed it!

2020-10-19 18:37 UTC, merged