add exception handling for todo skill
microsoft/botframework-solutions pull request #432
Opened 2018-12-12 08:28 UTC by feich-ms

Add exception handling for todo skill based on Ted's template
## Description
1. add skill exception for OneNote and Outlook API calls.
2. Log exception messages.

## Related Issue
fixes #415 

## Testing Steps
Try to add a todo item to a msa account without permissions to OneNote or Outlook.

2018-12-13 22:05 UTC, lauren-mills requested changes

2018-12-13 22:05 UTC, lauren-mills commented on solutions/Virtual-Assistant/src/csharp/skills/todoskill/Dialogs/Shared/Resources/ToDoSharedResponses.de.json
> +        "text": "Ich habe das leider nicht verstanden. K鰊nen Sie Ihr Anliegen bitte noch einmal anders formulieren?",
Check these changes out, because they don't look right.

2018-12-13 22:05 UTC, lauren-mills commented on solutions/Virtual-Assistant/src/csharp/skills/todoskill/Dialogs/Shared/Resources/ToDoSharedResponses.de.json
> +        "text": "Sorry, es sieht so aus, als w�re etwas schief gelaufen!",
Same here

2018-12-13 22:05 UTC, lauren-mills commented
I'll let @lzc850612 check out the exception handling changes to make sure they are consistent with his approach.

2018-12-13 23:23 UTC, lzc850612 approved these changes

2018-12-14 00:41 UTC, feich-ms commented on solutions/Virtual-Assistant/src/csharp/skills/todoskill/Dialogs/Shared/Resources/ToDoSharedResponses.de.json
> +        "text": "Ich habe das leider nicht verstanden. K鰊nen Sie Ihr Anliegen bitte noch einmal anders formulieren?",
I removed the de resouce file of ToDoSharedResponse. There are two reasons of doing this. One reason is that currently only ToDoSharedDialog has de resouce file and other dialogs don't include de file(we only have en and zh currently), which means the de locale will not work at all if only ToDoSharedDialog has de file. Another reason is that we have another issue item #284 tracking the work of all other locales. I think we should fix all the locale issues there.

2018-12-14 00:42 UTC, feich-ms commented on solutions/Virtual-Assistant/src/csharp/skills/todoskill/Dialogs/Shared/Resources/ToDoSharedResponses.de.json
> +        "text": "Sorry, es sieht so aus, als w�re etwas schief gelaufen!",
I removed ToDoSharedResponses.de.json. See comments above.

2018-12-14 15:36 UTC, lauren-mills approved these changes

2018-12-15 11:20 UTC, merged