[Email] Adjust luis model after sync with luis team
microsoft/botframework-solutions pull request #835
Opened 2019-02-20 12:31 UTC by DingmaomaoBJTU

## Description
[Email] Adjust luis model after sync with luis team

## Related Issue

[Email] Adjust luis model after sync with luis team #834

## Testing Steps

## Checklist
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated the appropriate unit tests
- [ ] I have tested any new/updated dialogs using Speech in the emulator to ensure the [Speak](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-text-to-speech?view=azure-bot-service-3.0) property is set to enable a high quality speech-first experience and the appropriate [InputHints](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-add-input-hints?view=azure-bot-service-3.0) are set correctly. 
- [ ] I have updated related documentation

If this contains changes that needs to be replicated between the Enterprise Template <-> Virtual Assistant
- [ ] A duplicate issue is filed to track future  work.

If you have updated responses or `.lu` files:
- [ ] All languages have been updated
- [ ] You have tested deployment with your new models

2019-02-20 17:41 UTC, lauren-mills requested changes

2019-02-20 17:41 UTC, lauren-mills commented on solutions/Virtual-Assistant/src/csharp/skills/emailskill/emailskill/CognitiveModels/LUIS/de/email.lu
> +## Confirm
This intent should be handled by the general model, right? If there is a particular reason you needed to add it back, please let us know. This will cause issues in the dispatch model

2019-02-20 17:41 UTC, lauren-mills commented on solutions/Virtual-Assistant/src/csharp/skills/emailskill/emailskill/CognitiveModels/LUIS/de/email.lu
> +## ShowNext
Same as above, you should be using the general model Next intent for this.

2019-02-20 17:41 UTC, lauren-mills commented on solutions/Virtual-Assistant/src/csharp/skills/emailskill/emailskill/CognitiveModels/LUIS/en/email.lu
> +## Cancel
See above.

2019-02-21 05:56 UTC, DingmaomaoBJTU commented on solutions/Virtual-Assistant/src/csharp/skills/emailskill/emailskill/CognitiveModels/LUIS/de/email.lu
> +## Confirm
As discussed in meeting, rename the confirm intent to ConfirmSend and remove all the duplicated utterances.

2019-02-21 19:53 UTC, lauren-mills commented on solutions/Virtual-Assistant/src/csharp/skills/emailskill/emailskill/CognitiveModels/LUIS/de/email.lu
> +- "Okay, send it now"
These look like they're still in english but this is the german file

2019-02-21 19:53 UTC, lauren-mills commented on solutions/Virtual-Assistant/src/csharp/skills/emailskill/emailskill/CognitiveModels/LUIS/de/email.lu
> +- "Okay, send it now"
I think its due to the quotes being included in the utterance

2019-02-21 19:56 UTC, lauren-mills commented on solutions/Virtual-Assistant/src/csharp/skills/emailskill/emailskill/Dialogs/ShowEmail/Resources/ShowEmailResponses.json
> +        "speak": "Do you want to see the content of the first email? I can read out any email for you, just let me know by naming out the subject or from whom.",
These look like they are swapped. Speak should be "hear" and text should be "see"

2019-02-21 19:56 UTC, lauren-mills approved these changes
This looks okay, just take a look at the small comments

2019-02-22 08:27 UTC, DingmaomaoBJTU commented on solutions/Virtual-Assistant/src/csharp/skills/emailskill/emailskill/Dialogs/ShowEmail/Resources/ShowEmailResponses.json
> +        "speak": "Do you want to see the content of the first email? I can read out any email for you, just let me know by naming out the subject or from whom.",
Good catch! Thanks!

2019-02-22 08:30 UTC, DingmaomaoBJTU commented on solutions/Virtual-Assistant/src/csharp/skills/emailskill/emailskill/CognitiveModels/LUIS/de/email.lu
> +- "Okay, send it now"
Seems only de have this problems~ So fix de only. Thanks!

2019-02-22 09:27 UTC, merged