Refactor documentation to be more discoverable and easier to get started
microsoft/botframework-solutions pull request #881
Opened 2019-02-26 21:52 UTC by ryanlengel

## Description

This is a large refactor of where we store our docs to make them easier to get started and discoverable to new users. I'm opening this as a draft PR for now, I appreciate any feedback you have on the new layout/content.

### Maintenance
Close #852 
* Move all docs under `\root\docs\`  
  * As it stands docs are stored under both `root\solutions\virtual-assistant\docs` and `\root\solutions\analytics` but as we have seen these already have direct overlap.
  * This provides the added benefit of integrating with [Github Pages](https://help.github.com/en/categories/github-pages-basics) in the future if we wish.
* Reorganize docs directories into related buckets  
  * Analytics, Skills, Virtual Assistant, Media, Transcripts
* Standardize skill documentation
* Update skill docs with latest scenario & language model scenarios
* Consolidate Virtual Assistant pages for small docs  
* Add link to analytics in main readme
* Add unit test overview to the VA testing doc
* Updated writing style to be closed to Microsoft writing style guide

## Checklist

- [x] I have updated related documentation

2019-02-26 22:58 UTC, lzc850612 approved these changes

2019-02-26 23:23 UTC, lauren-mills approved these changes

2019-02-27 12:19 UTC, darrenj requested changes
I've done a pass through, big improvement! Thanks for doing this. We should probably look to add transcripts to all skill documentation (eg productivity too)

2019-02-27 12:19 UTC, darrenj commented on docs/virtual-assistant/README.md
> +[Experimental Skills](../skills/experimental-Skills.md) | Experimental Skills are early prototypes of Skills to help bring Skill concepts to life for demonstrations and proof-of-concepts along with p
broken link

2019-02-27 12:31 UTC, darrenj commented on docs/virtual-assistant/README.md
> +[Experimental Skills](../skills/experimental-Skills.md) | Experimental Skills are early prototypes of Skills to help bring Skill concepts to life for demonstrations and proof-of-concepts along with p
Also this functionality isn't there yet in calendar :)

Find a Meeting Room 
•	Book a conference room
•	Can you reserve room 258 on Thursday at 1 PM?

2019-03-05 20:17 UTC, ryanlengel commented
@darrenj updated docs addressing your comments & merged in the changes happening on master branch.

2019-03-06 10:35 UTC, darrenj approved these changes

2019-03-06 10:58 UTC, merged

2019-03-06 10:59 UTC, darrenj commented
PR issue is due to this branch being out of sync with main code branch and changes to skill welcome message. Should be resolved once merged