[Calendar] update luis model
microsoft/botframework-solutions pull request #894
Opened 2019-03-01 08:16 UTC by KayMKM

## Description

calendar luis model update to v1.3.1. zh-cn version is v1.3

### Architecture

### Bug Fixes

### Conversational Experience

### Maintenance

### Language Understanding

## Testing Steps

## Checklist

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated the appropriate unit tests
- [ ] I have tested any new/updated dialogs using Speech in the emulator to ensure the [Speak](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-text-to-speech?view=azure-bot-service-3.0) property is set to enable a high quality speech-first experience and the appropriate [InputHints](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-add-input-hints?view=azure-bot-service-3.0) are set correctly. 
- [ ] I have updated related documentation

- [ ] A duplicate issue is filed to track future  work.

- [ ] All languages have been updated
- [ ] You have tested deployment with your new models

2019-03-01 20:43 UTC, lauren-mills requested changes

2019-03-01 20:43 UTC, lauren-mills commented on solutions/Virtual-Assistant/src/csharp/skills/calendarskill/calendarskill/CognitiveModels/LUIS/en/calendar.lu
> +> ! Automatically generated by [LUDown CLI](https://github.com/Microsoft/botbuilder-tools/tree/master/Ludown), Fri Mar 01 2019 15:40:28 GMT+0800 (China Standard Time)
In these new lu files it doesn't have the "datetime" prebuilt entity, but the code looks for it in the CalendarLU.cs class. If you regenerate the CalendarLU.cs file it will cause build errors.  Please run the update_published_models.ps1 script before making PRs for the LU files to make sure they won't create any build issues when devs run them.

2019-03-04 11:35 UTC, KayMKM commented on solutions/Virtual-Assistant/src/csharp/skills/calendarskill/calendarskill/CognitiveModels/LUIS/en/calendar.lu
> +> ! Automatically generated by [LUDown CLI](https://github.com/Microsoft/botbuilder-tools/tree/master/Ludown), Fri Mar 01 2019 15:40:28 GMT+0800 (China Standard Time)
added the datetimev2 entitiy in lu file

2019-03-04 17:51 UTC, lauren-mills approved these changes

2019-03-05 03:11 UTC, merged