Added nuget package to VA and Skills
microsoft/botframework-solutions pull request #953
Opened 2019-03-08 20:31 UTC by lauren-mills

## Description
- Installed Microsoft.Bot.Builder.Solutions package from myget
- Removed Microsoft.Bot.Solutions package
- Changed namespace throughout

To do:
- [ ] Update docs to add myget as package source

Future PRs:
- [ ] Update skill template to use package

2019-03-11 21:21 UTC, lzc850612 requested changes

2019-03-11 21:21 UTC, lzc850612 commented on lib/csharp/VirtualAssistant.ruleset
> +﻿<?xml version="1.0" encoding="utf-8"?>
maybe we should name this file 'Microsoft.Bot.Builder.Solutions.ruleset'

2019-03-11 21:21 UTC, lzc850612 commented on solutions/Virtual-Assistant/src/csharp/VirtualAssistant.sln
> +Project("{2150E333-8FDC-42A3-9474-1A3956D46DE8}") = "Skills", "Skills", "{35B7FB90-4866-40C9-AD92-CEB5784CF034}"
second "skills" should be lower case since it's the actual folder name and we want them to be lowercase at that level

2019-03-12 16:12 UTC, lauren-mills commented on solutions/Virtual-Assistant/src/csharp/VirtualAssistant.sln
> +Project("{2150E333-8FDC-42A3-9474-1A3956D46DE8}") = "Skills", "Skills", "{35B7FB90-4866-40C9-AD92-CEB5784CF034}"
Any idea why it automatically changes this even though my physical folders are lowercase?

2019-03-12 19:18 UTC, lzc850612 approved these changes

2019-03-12 19:19 UTC, merged

2019-03-13 14:28 UTC, outofthecave commented
@lauren-mills Is there anything that I need to update in Visual Studio for this to work?  I'm getting some errors:
![image](https://user-images.githubusercontent.com/4209873/54286616-8b7c0c00-457a-11e9-875f-f6595c1b0e23.png)

2019-03-13 15:41 UTC, lauren-mills commented
@outofthecave, I’ve added the package source in the nuget.config for the solution, so you shouldn’t have to add anything manually... can you verify that the file is there? And can you see the extra package source in the Package Manager Settings window?

2019-03-14 13:52 UTC, outofthecave commented
Thanks, @lauren-mills.  The file `solutions/Virtual-Assistant/src/csharp/nuget.config` is present and contains an entry for MyGet.  But the package source is not showing up in Visual Studio when I right-click on "Virtual Assistant", select "Manage NuGet Packages", and check the "Package source" drop-down.  If I click the little gear next to that drop-down to get to the settings window, it's not showing up either.  I only see "nuget.org" and "Microsoft Visual Studio Offline Packages" in both places.

2019-03-14 14:03 UTC, outofthecave commented
Never mind, it turns out this was one of those issues with file name capitalization that only show up on my end because I use the WSL for git operations.  I'll make a PR to correct the capitalization of the file name.